using DNSoft.eWF.FrameWork.Data.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bayer.eWF.BSL.Common
{
    public class CommonContext : WorkflowContext
    {
        public const string USP_SELECT_CODE_SUB = "[dbo].[USP_SELECT_CODE_SUB] @CLASS_CODE";

        public const string USP_SELECT_DOCUMENT_LIST = "[dbo].[USP_SELECT_DOCUMENT_LIST] @COMPANY_CODE";

        public const string USP_SELECT_BUSINESS_PLACE = "[eManage].[dbo].[USP_SELECT_BUSINESS_PLACE] @COMPANY_CODE";

        public const string USP_SELECT_COMPANY = "[eManage].[dbo].[USP_SELECT_COMPANY] @KEYWORD";

        public const string USP_SELECT_BAYER_COMPANY = "[eManage].[dbo].[USP_SELECT_BAYER_COMPANY]";

        public const string USP_SELECT_CUSTOMER = "[eManage].[dbo].[USP_SELECT_CUSTOMER] @COMPANY_CODE, @BU, @PARVW, @KEYWORD, @LEVEL";

        public const string USP_SELECT_MEMBERSHIP = "[dbo].[USP_SELECT_MEMBERSHIP]"; //EMANAGE 마스터 에서 Membership application으로 변경

        public const string USP_SELECT_PRODUCT = "[eManage].[dbo].[USP_SELECT_PRODUCT] @COMPANY_CODE, @BU, @KEYWORD, @BASE_PRICE, @SAMPLE_TYPE, @EXIST_SAMPLE";

        public const string USP_SELECT_COUNTRY = "[eManage].[dbo].[USP_SELECT_COUNTRY]";

        public const string USP_SELECT_CITY = "[eManage].[dbo].[USP_SELECT_CITY] @COUNTRY";
        
        public const string USP_SELECT_DOCTOR = "[eManage].[dbo].[USP_SELECT_DOCTOR] @KEYWORD";

        public const string USP_SELECT_PHARMACY = "[eManage].[dbo].[USP_SELECT_PHARMACY] @KEYWORD";

        public const string USP_SELECT_COMMON_P_I_ACTIVITY = "[dbo].[USP_SELECT_COMMON_P_I_ACTIVITY] @YEAR";

        public const string USP_SELECT_COMMON_AH_P_I_ACTIVITY = "[dbo].[USP_SELECT_COMMON_AH_P_I_ACTIVITY] @YEAR";

        public const string USP_SELECT_CUSTOMER_MASTER = "[eManage].[dbo].[USP_SELECT_CUSTOMER_MASTER] @COMPANY_TYPE, @BU_TYPE,@PARVW,@VISIBILITY,@KPIS, @KEYWORD";

        public const string USP_SELECT_CUSTOMER_MASTER_KPIS = "[eManage].[dbo].[USP_SELECT_CUSTOMER_MASTER_KPIS] @COMPANY_TYPE, @BU_TYPE, @KEYWORD";

        public const string USP_UPDATE_CUSTOMER_MASTER = "[eManage].[dbo].[USP_UPDATE_CUSTOMER_MASTER] @CUSTOMER_CODE, @PARVW, @CUSTOMER_NAME, @CUSTOMER_NAME_KR, @COMPANY_CODE, @BU, @LEVEL, @SALES_RATE, @SCORING_RATE, @CREDIT_LIMIT, @MORTAGE, @VISIBILITY, @CHANNEL, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_UPDATE_CUSTOMER_MASTER_KPIS = "[eManage].[dbo].[USP_UPDATE_CUSTOMER_MASTER_KPIS] @BCNC_CODE,@BIZR_NO,@BCNC_NM,@BCNC_RPRSNTV,@BCNC_SE,@TELNO,@POST_CODE,@POST_ADRES,@UPDATER_ID,@UPDATE_DATE";

        public const string USP_DELETE_CUSTOMER_MASTER_KPIS = "[eManage].[dbo].[USP_DELETE_CUSTOMER_MASTER_KPIS] @BCNC_CODE,@UPDATER_ID";

        public const string USP_SELECT_CUSTOMER_BU_LIST = "[eManage].[dbo].[USP_SELECT_CUSTOMER_BU_LIST] @COMPANY_CODE";

        public const string USP_UPDATE_CUSTOMER_MASTER_CREDIT_LIMIT = "[eManage].[dbo].[USP_UPDATE_CUSTOMER_MASTER_CREDIT_LIMIT] @CUSTOMER_CODE, @PARVW, @CREDIT_LIMIT, @UPDATER_ID";

        public const string USP_SELECT_PRODUCT_MASTER = "[eManage].[dbo].[USP_SELECT_PRODUCT_MASTER] @COMPANY_TYPE, @BU_TYPE,@VISIBILITY,@KPIS, @KEYWORD";
        public const string USP_SELECT_PRODUCT_MASTER_KPIS = "[eManage].[dbo].[USP_SELECT_PRODUCT_MASTER_KPIS] @COMPANY_TYPE, @BU_TYPE, @KEYWORD";

        public const string USP_UPDATE_PRODUCT_MASTER = "[eManage].[dbo].[USP_UPDATE_PRODUCT_MASTER] @PRODUCT_CODE, @PRODUCT_NAME,@PRODUCT_NAME_KR, @COMPANY_CODE, @BU, @BASE_PRICE, @SAMPLE_CODE, @SAMPLE_TYPE, @USE_SAMPLE_DC, @MRP_FLAG, @MARGIN, @INVOICE_PRICE, @NET1_PRICE, @NET2_PRICE, @INVOICE_PRICE_NH, @NET1_PRICE_NH, @NET2_PRICE_NH,@VISIBILITY, @UPDATER_ID, @UPDATE_DATE";
        public const string USP_UPDATE_PRODUCT_MASTER_KPIS = "[eManage].[dbo].[USP_UPDATE_PRODUCT_MASTER_KPIS] @PRDUCT_CODE,@PRODUCT_NAME_KR,@STD_CODE,@REPRSNT_CODE,@REPRSNT_NM,@REPORT_YN,@PACKNG_QY,@C_STD_CODE,@C_PRODUCT_KOR_NM,@C_REPRSNT_CODE,@C_PEPRSNT_NM,@C_PACKNG_QY,@MULTIPLICATION,@UPDATER_ID,@UPDATE_DATE";
        public const string USP_DELETE_PRODUCT_MASTER_KPIS = "[eManage].[dbo].[USP_DELETE_PRODUCT_MASTER_KPIS] @PRDUCT_CODE,@UPDATER_ID";

        public const string USP_SELECT_PRODUCT_BU_LIST = "[eManage].[dbo].[USP_SELECT_PRODUCT_BU_LIST] @SEARCH_TYPE";

        public const string USP_SELECT_ADMIN_DOC_LIST = "[dbo].[USP_SELECT_ADMIN_DOC_LIST] @USER_ID";

        public const string USP_SELECT_ADMIN_DOC_LIST_DETAILREPORT = "[dbo].[USP_SELECT_ADMIN_DOC_LIST_DETAILREPORT] @USER_ID";

        public static string USP_SELECT_COUNTRY_MASTER = "[eManage].[dbo].[USP_SELECT_COUNTRY_MASTER] @KEYWORD";
        //2015.06.15 신규 추가 (Product 신규데이터 등록)
        public const string USP_INSERT_PRODUCT_MASTER = "[eManage].[dbo].[USP_INSERT_PRODUCT_MASTER] @PRODUCT_CODE, @PRODUCT_NAME, @PRODUCT_NAME_KR,@COMPANY_CODE, @BU, @BASE_PRICE, @CREATOR_ID, @CREATE_DATE";
        //2015.06.15 신규 추가 (Customer 신규데이터 등록)
        public const string USP_INSERT_PRODUCT_MASTER_KPIS = "[eManage].[dbo].[USP_INSERT_PRODUCT_MASTER_KPIS] @PRDUCT_CODE,@STD_CODE,@REPRSNT_CODE,@REPRSNT_NM,@REPORT_YN,@PACKNG_QY,@C_PACKNG_QY,@CREATOR_ID,@CREATE_DATE ";
        public const string USP_INSERT_CUSTOMER_MASTER = "[eManage].[dbo].[USP_INSERT_CUSTOMER_MASTER] @CUSTOMER_CODE, @PARVW, @CUSTOMER_NAME, @CUSTOMER_NAME_KR, @COMPANY_CODE, @BU, @CHANNEL, @CREATOR_ID, @CREATE_DATE";
        public const string USP_INSERT_CUSTOMER_MASTER_KPIS = "[eManage].[dbo].[USP_INSERT_CUSTOMER_MASTER_KPIS] @BCNC_CODE,@BIZR_NO,@BCNC_NM,@BCNC_RPRSNTV,@BCNC_SE,@TELNO,@POST_CODE,@POST_ADRES,@CREATOR_ID,@CREATE_DATE";
        //2015.06.55 신규 추가 (LOGIN_HISTORY 등록)

        public const string USP_INSERT_LOGIN_HISTORY = "[eManage].[dbo].[USP_INSERT_LOGIN_HISTORY] @USER_ID, @CLIENTIP, @WINDOWUSERNAME, @WINDOWDOMAINNAME";
        //2015.06.55 신규 추가 (LOGIN_HISTORY 조회)
        public const string USP_SELECT_LOGIN_HISTORY = "[eManage].[dbo].[USP_SELECT_LOGIN_HISTORY] @USER_ID";

    }
}
