using DNSoft.eWF.FrameWork.Data.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bayer.eWF.BSL.Approval
{
    public class ApprovalContext : WorkflowContext
    {

        #region USP_CREATE_PROCESS_ID
        public const string USP_CREATE_PROCESS_ID = "[dbo].[USP_CREATE_PROCESS_ID]";
        #endregion

        #region USP_INSERT_PROCESS_APPROVER_ADDTIONAL
        public const string USP_INSERT_PROCESS_APPROVER_ADDTIONAL = "[dbo].[USP_INSERT_PROCESS_APPROVER_ADDTIONAL] @PROCESS_ID, @IDX, @APPROVAL_TYPE, @USER_ID, @CREATE_DATE";
        #endregion

        #region USP_DELETE_PROCESS_APPROVER_ADDTIONAL
        public const string USP_DELETE_PROCESS_APPROVER_ADDTIONAL = "[dbo].[USP_DELETE_PROCESS_APPROVER_ADDTIONAL] @PROCESS_ID, @APPROVAL_TYPE";
        #endregion


        #region USP_SELECT_APPROVAL_LINE
        public const string USP_SELECT_APPROVAL_LINE = "[dbo].[USP_SELECT_APPROVAL_LINE] @DOCUMENT_ID, @USER_ID ,@PROCESS_ID";
        #endregion

        #region USP_INSERT_PROCESS_DOCUMENT
        public const string USP_INSERT_PROCESS_DOCUMENT = "[dbo].[USP_INSERT_PROCESS_DOCUMENT] @PROCESS_ID,@DOCUMENT_ID, @DOC_NAME, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUEST_DATE, @COMPANY_CODE, @REQUESTER_ID, @CURRENT_APPROVER, @FINAL_APPROVER, @REJECTED_PROCESS_ID, @CREATE_DATE, @UPDATE_DATE";
        #endregion

        #region USP_INSERT_PROCESS_APPROVER
        public const string USP_INSERT_PROCESS_APPROVER = "[dbo].[USP_INSERT_PROCESS_APPROVER] @PROCESS_ID, @APPROVAL_TYPE, @APPROVAL_SEQ, @APPROVER_TYPE, @APPROVER_ID, @APPROVER_ORG_NAME, @ABSENCE_APPROVER_ID, @ABSENCE_APPROVER_ORG_NAME, @STATUS, @SENT_MAIL, @APPROVAL_DATE, @COMMENT, @CREATE_DATE, @UPDATE_DATE";
        #endregion

        #region USP_DELETE_PROCESS_APPROVER
        public const string USP_DELETE_PROCESS_APPROVER = "[dbo].[USP_DELETE_PROCESS_APPROVER] @PROCESS_ID";
        #endregion

        #region USP_UPDATE_DOCUMENT_PROCESS_STATUS
        public const string USP_UPDATE_DOCUMENT_PROCESS_STATUS = "[DBO].[USP_UPDATE_DOCUMENT_PROCESS_STATUS] @DOCUMENT_ID, @PROCESS_ID, @PROCESS_STATUS, @APPROVER_ID";
        #endregion

        #region USP_INSERT_COMMON_ABSENCE
        public const string USP_INSERT_COMMON_ABSENCE = "[dbo].[USP_INSERT_COMMON_ABSENCE] @USER_ID, @APPROVER_ID, @FROM_DATE, @TO_DATE, @DESCRIPTION";
        #endregion

        #region USP_SELECT_ABSENCE_LIST
        public const string USP_SELECT_ABSENCE_LIST = "[dbo].[USP_SELECT_ABSENCE_LIST] @USER_ID";
        #endregion

        #region USP_DELETE_COMMON_ABSENCE
        public const string USP_DELETE_ABSENSE = "[dbo].[USP_DELETE_ABSENSE] @IDX";
        #endregion

        #region USP_SELECT_ABSENCE
        public const string USP_SELECT_ABSENCE = "[dbo].[USP_SELECT_ABSENCE] @IDX";
        #endregion

        #region USP_UPDATE_COMMON_ABSENCE
        public const string USP_UPDATE_COMMON_ABSENCE = "[dbo].[USP_UPDATE_COMMON_ABSENCE] @IDX, @APPROVER_ID, @FROM_DATE, @TO_DATE, @DESCRIPTION";
        #endregion

        #region USP_SELECT_APPROVAL_TODO_LIST
        public const string USP_SELECT_APPROVAL_TODO_LIST = "[dbo].[USP_SELECT_APPROVAL_TODO_LIST] @SEARCH_TYPE, @SEARCH_TEXT, @DATE_USEYN, @START_DATE, @END_DATE, @CURRENT_APPROVER";
        #endregion

        #region USP_SELECT_PROCESS_APPROVER_USER
        public const string USP_SELECT_PROCESS_APPROVER_USER = "[dbo].[USP_SELECT_PROCESS_APPROVER_USER] @PROCESS_ID, @APPROVER_ID";
        #endregion

        #region USP_SELECT_PROCESS_APPROVER_LIST
        public const string USP_SELECT_PROCESS_APPROVER_LIST = "[dbo].[USP_SELECT_PROCESS_APPROVER_LIST] @PROCESS_ID";
        #endregion

        #region USP_SELECT_DOC_LOG_LIST
        public const string USP_SELECT_DOC_LOG_LIST = "[dbo].[USP_SELECT_DOC_LOG_LIST] @PROCESS_ID";
        #endregion

        #region USP_UPDATE_PROCESS_DOCUMENT_STATUS
        public const string USP_UPDATE_PROCESS_DOCUMENT_STATUS = "[dbo].[USP_UPDATE_PROCESS_DOCUMENT_STATUS] @PROCESS_ID, @APPROVER_ID, @PROCESS_STATUS";
        #endregion

        #region USP_INSERT_DOC_LOG
        public const string USP_INSERT_DOC_LOG = "[dbo].[USP_INSERT_DOC_LOG] @PROCESS_ID, @REGISTER_ID, @LOG_TYPE, @COMMENT, @CREATE_DATE";
        #endregion

        #region USP_UPDATE_PROCESS_APPROVER
        public const string USP_UPDATE_PROCESS_APPROVER = "[dbo].[USP_UPDATE_PROCESS_APPROVER] @PROCESS_ID, @APPROVER_ID, @STATUS, @COMMENT";
        #endregion


        #region USP_INSERT_PROCESS_APPROVER_FORWARDAPPROVAL_USER
        public const string USP_INSERT_PROCESS_APPROVER_FORWARDAPPROVAL_USER = "[dbo].[USP_INSERT_PROCESS_APPROVER_FORWARDAPPROVAL_USER] @PROCESS_ID, @USER_ID, @APPROVER_ID";
        #endregion

        #region USP_SELECT_DOCUMENT_FINAL_APPROVER_ID
        public const string USP_SELECT_DOCUMENT_FINAL_APPROVER_ID = "[dbo].[USP_SELECT_DOCUMENT_FINAL_APPROVER_ID] @PROCESS_ID";
        #endregion

        #region USP_SELECT_DOCUMENT_FINAL_APPROVER_ID_LINE
        public const string USP_SELECT_DOCUMENT_FINAL_APPROVER_ID_LINE = "[dbo].[USP_SELECT_DOCUMENT_FINAL_APPROVER_ID_LINE] @PROCESS_ID";
        #endregion

        #region USP_UPDATE_PROCESS_DOCUMENT_FINAL_APPROVER
        public const string USP_UPDATE_PROCESS_DOCUMENT_FINAL_APPROVER = "[dbo].[USP_UPDATE_PROCESS_DOCUMENT_FINAL_APPROVER] @PROCESS_ID, @APPROVER_ID";
        #endregion

        #region USP_UPDATE_PROCESS_COMPLETED
        public const string USP_UPDATE_PROCESS_COMPLETED = "[dbo].[USP_UPDATE_PROCESS_COMPLETED] @DOCUMENT_ID, @PROCESS_ID, @PROCESS_STATUS, @APPROVER_ID";
        #endregion

        #region USP_MERGE_PROCESS_APPROVER_COMPLETED_ADD_REVIEWER
        public const string USP_MERGE_PROCESS_APPROVER_COMPLETED_ADD_REVIEWER = "[dbo].[USP_MERGE_PROCESS_APPROVER_COMPLETED_ADD_REVIEWER] @PROCESS_ID, @APPROVAL_TYPE, @APPROVAL_SEQ, @APPROVER_TYPE, @APPROVER_ID, @APPROVER_ORG_NAME, @ABSENCE_APPROVER_ID, @ABSENCE_APPROVER_ORG_NAME, @STATUS, @SENT_MAIL, @APPROVAL_DATE, @COMMENT";
        #endregion

        #region USP_SELECT_APPROVAL_SAVED_LIST
        public const string USP_SELECT_APPROVAL_SAVED_LIST = "[dbo].[USP_SELECT_APPROVAL_SAVED_LIST] @SEARCH_TYPE, @SEARCH_TEXT, @DATE_USEYN, @START_DATE, @END_DATE, @REQUESTER_ID";
        #endregion

        #region USP_SELECT_APPROVAL_PROECESSING_LIST
        public const string USP_SELECT_APPROVAL_PROECESSING_LIST = "[dbo].[USP_SELECT_APPROVAL_PROECESSING_LIST] @SEARCH_TYPE, @SEARCH_TEXT, @DATE_USEYN, @START_DATE, @END_DATE, @REQUESTER_ID";
        #endregion

        #region USP_SELECT_APPROVAL_COMPLETED_LIST
        public const string USP_SELECT_APPROVAL_COMPLETED_LIST = "[dbo].[USP_SELECT_APPROVAL_COMPLETED_LIST] @SEARCH_TYPE, @SEARCH_TEXT, @DATE_USEYN, @START_DATE, @END_DATE, @USER_ID";
        #endregion

        #region USP_SELECT_APPROVAL_COMPLETED_COLLATERAL_LIST
        public const string USP_SELECT_APPROVAL_COMPLETED_COLLATERAL_LIST = "[dbo].[USP_SELECT_APPROVAL_COMPLETED_COLLATERAL_LIST] @BG, @TYPE, @KEYWORD, @USER_ID";
        #endregion

        #region USP_SELECT_SENDMAIL_TO_ADDRESS_LIST
        public const string USP_SELECT_SENDMAIL_TO_ADDRESS_LIST = "[dbo].[USP_SELECT_SENDMAIL_TO_ADDRESS_LIST] @PROCESS_ID, @MAILSENDTYPE";
        #endregion

        #region USP_SELECT_RETURN_GOODS_MAILADDRESS
        public const string USP_SELECT_RETURN_GOODS_MAILADDRESS = "[dbo].[USP_SELECT_RETURN_GOODS_MAILADDRESS] @USER_ID";
        #endregion

        #region USP_UPDATE_PROCESS_APPROVER_SENT_MAIL
        public const string USP_UPDATE_PROCESS_APPROVER_SENT_MAIL = "[dbo].[USP_UPDATE_PROCESS_APPROVER_SENT_MAIL] @PROCESS_ID, @APPROVER_ID, @SPLIT";

        public const string USP_UPDATE_PROCESS_APPROVER_SENT_MAIL_COMMENT = "[dbo].[USP_UPDATE_PROCESS_APPROVER_SENT_MAIL_COMMENT] @PROCESS_ID, @STATUS, @APPROVER_ID, @SPLIT";
        #endregion

        #region USP_SELECT_SEND_NOTICEMAIL_LIST
        public const string USP_SELECT_SEND_NOTICEMAIL_LIST = "[dbo].[USP_SELECT_SEND_NOTICEMAIL_LIST] @BASICDATE";
        #endregion

        #region USP_SELECT_APPROVAL_REJECT_LIST
        public const string USP_SELECT_APPROVAL_REJECT_LIST = "[dbo].[USP_SELECT_APPROVAL_REJECT_LIST] @SEARCH_TYPE, @SEARCH_TEXT, @DATE_USEYN, @START_DATE, @END_DATE, @REQUESTER_ID";
        #endregion

        #region USP_SELECT_APPROVAL_WITHDRAW_LIST
        public const string USP_SELECT_APPROVAL_WITHDRAW_LIST = "[dbo].[USP_SELECT_APPROVAL_WITHDRAW_LIST] @SEARCH_TYPE, @SEARCH_TEXT, @DATE_USEYN, @START_DATE, @END_DATE, @REQUESTER_ID";
        #endregion

        #region USP_SELECT_APPROVAL_IS_COMPLETED
        public const string USP_SELECT_APPROVAL_IS_COMPLETED = "[dbo].[USP_SELECT_APPROVAL_IS_COMPLETED]  @PROCESS_ID";
        #endregion

        #region USP_SELECT_APPROVAL_CNT
        public const string USP_SELECT_APPROVAL_CNT = "[dbo].[USP_SELECT_APPROVAL_CNT]  @REQUESTER_ID, @CNT_TYPE";
        #endregion

        #region [ USP_DELETE_DOCUMENT_PROCESS ]

        public const string USP_DELETE_DOCUMENT_PROCESS = "[dbo].[USP_DELETE_DOCUMENT_PROCESS] @PROCESS_ID_LIST";

        #endregion

        #region [ USP_SELECT_PROCESS_DOCUMENT_STATUS ]

        public const string USP_SELECT_PROCESS_DOCUMENT_STATUS = "[dbo].[USP_SELECT_PROCESS_DOCUMENT_STATUS] @PROCESS_ID";

        #endregion

        #region [ USP_INSERT_PROCESS_APPROVER_COMPLETED ]

        public const string USP_INSERT_PROCESS_APPROVER_COMPLETED = "[dbo].[USP_INSERT_PROCESS_APPROVER_COMPLETED] @PROCESS_ID";

        #endregion

        #region [ USP_SELECT_PROCESS_REJECT_USER ]

        public const string USP_SELECT_PROCESS_REJECT_USER = "[dbo].[USP_SELECT_PROCESS_REJECT_USER] @PROCESS_ID";

        #endregion

        #region [ USP_SELECT_INPUT_COMMENT ]

        public const string USP_SELECT_INPUT_COMMENT = "[dbo].[USP_SELECT_INPUT_COMMENT] @PROCESS_ID";

        #endregion

        #region [ USP_SELECT_DOCUMENT_AUTH_USER ]

        public const string USP_SELECT_DOCUMENT_AUTH_USER = "[dbo].[USP_SELECT_DOCUMENT_AUTH_USER] @PROCESS_ID, @USER_ID";

        #endregion

        #region [USP_SELECT_APPROVAL_LIST]
        public const string USP_SELECT_APPROVAL_LIST = "[dbo].[USP_SELECT_APPROVAL_LIST] @SEARCH_TYPE, @SEARCH_TEXT, @DATE_USEYN, @START_DATE, @END_DATE";

        public const string USP_SELECT_APPROVAL_ADMIN_VIEW_LIST = "[dbo].[USP_SELECT_APPROVAL_ADMIN_VIEW_LIST] @SEARCH_TYPE, @SEARCH_TEXT, @DATE_USEYN, @START_DATE, @END_DATE, @USER_ID";
        #endregion

        #region [USP_SELECT_WITHHOLDING]
        public const string USP_SELECT_WITHHOLDING = "[dbo].[USP_SELECT_WITHHOLDING]  @SEARCH_TEXT,  @START_DATE, @END_DATE";
        #endregion

        #region [USP_REPORTING_DOCUMENT]

        public const string USP_REPORTING_DOCUMENT = "[dbo].[USP_REPORTING_DOCUMENT] @DOCUMNET_ID,@FROM_DATE,@TO_DATE";
        #endregion

        


        #region [ 1. Travel Management ]

        public const string USP_MERGE_TRAVEL_MANAGEMENT = "[dbo].[USP_MERGE_TRAVEL_MANAGEMENT] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TRIP_PURPOSE_CODE, @TRIP_PURPOSE, @TRIP_PERIOD_FROM, @TRIP_PERIOD_TO, @TRIP_INFO, @TRIP_CONTACT_POINT, @REQUESTED_TO_AGENCY, @QUOTATION_NUM, @REASON_CODE, @REASON_DESC, @COMMENT_TO_AGENCY, @AIRFARE_AMOUNT, @AIRFARE_COMMENT, @IS_DISUSED, @CREATOR_ID";

        public const string USP_INSERT_TRAVEL_MANAGEMENT_TRAVELER = "[dbo].[USP_INSERT_TRAVEL_MANAGEMENT_TRAVELER] @PROCESS_ID, @IDX, @TRAVELER_TYPE, @TRAVELER_ID, @TRAVELER_NAME, @SEX, @EMP_NO, @DIV_DEPT, @COMPANY_ORG, @COST_CODE, @INTERNAL_ORDER, @CREATOR_ID";

        public const string USP_DELETE_TRAVEL_MANAGEMENT_TRAVELER_ALL = "[dbo].[USP_DELETE_TRAVEL_MANAGEMENT_TRAVELER_ALL] @PROCESS_ID";

        public const string USP_DELETE_TRAVEL_MANAGEMENT_TRAVELER = "[dbo].[USP_DELETE_TRAVEL_MANAGEMENT_TRAVELER] @PROCESS_ID, @IDX, @TRAVELER_TYPE";

        public const string USP_INSERT_TRAVEL_MANAGEMENT_ROUTE = "[dbo].[USP_INSERT_TRAVEL_MANAGEMENT_ROUTE] @PROCESS_ID, @IDX, @DEPARTURE_DATE, @RETURN_DATE, @DEPARTURE_CODE, @ARRIVAL_CODE, @TRIP_TYPE, @TRIP_TYPE_NAME, @AIRPLANE_CLASS, @AIRPLANE_CLASS_NAME, @CREATOR_ID";

        public const string USP_DELETE_TRAVEL_MANAGEMENT_ROUTE_ALL = "[dbo].[USP_DELETE_TRAVEL_MANAGEMENT_ROUTE_ALL] @PROCESS_ID";

        public const string USP_DELETE_TRAVEL_MANAGEMENT_ROUTE = "[dbo].[USP_DELETE_TRAVEL_MANAGEMENT_ROUTE] @PROCESS_ID, @IDX";

        public const string USP_INSERT_TRAVEL_MANAGEMENT_ACCOMMODATION = "[dbo].[USP_INSERT_TRAVEL_MANAGEMENT_ACCOMMODATION] @PROCESS_ID, @IDX, @ACCOMMODATION_CODE, @ACCOMMODATION_NAME, @FROM_DATE, @TO_DATE, @AMOUNT_PER_NIGHT, @AMOUNT_TOTAL, @REASON_HOTEL, @CREATOR_ID";

        public const string USP_DELETE_TRAVEL_MANAGEMENT_ACCOMMODATION_ALL = "[dbo].[USP_DELETE_TRAVEL_MANAGEMENT_ACCOMMODATION_ALL] @PROCESS_ID";

        public const string USP_DELETE_TRAVEL_MANAGEMENT_ACCOMMODATION = "[dbo].[USP_DELETE_TRAVEL_MANAGEMENT_ACCOMMODATION] @PROCESS_ID, @IDX";

        public const string USP_SELECT_TRAVEL_MANAGEMENT = "[dbo].[USP_SELECT_TRAVEL_MANAGEMENT] @PROCESS_ID";

        public const string USP_SELECT_TRAVEL_MANAGEMENT_TRAVELER = "[dbo].[USP_SELECT_TRAVEL_MANAGEMENT_TRAVELER] @PROCESS_ID";

        public const string USP_SELECT_TRAVEL_MANAGEMENT_ROUTE = "[dbo].[USP_SELECT_TRAVEL_MANAGEMENT_ROUTE] @PROCESS_ID";

        public const string USP_SELECT_TRAVEL_MANAGEMENT_ACCOMMODATION = "[dbo].[USP_SELECT_TRAVEL_MANAGEMENT_ACCOMMODATION] @PROCESS_ID";

        public const string USP_UPDATE_TRAVEL_MANAGEMENT_REQUEST_TO_AGENCY = "[dbo].[USP_UPDATE_TRAVEL_MANAGEMENT_REQUEST_TO_AGENCY] @PROCESS_ID, @UPDATER_ID";

        public const string USP_SELECT_TRAVEL_MANAGEMENT_CALENDAR = "[dbo].[USP_SELECT_TRAVEL_MANAGEMENT_CALENDAR] @PROCESS_ID";

        #endregion

        #region [ 2. Business Card ]

        public const string USP_SELECT_BUSINESS_CARD = "[dbo].[USP_SELECT_BUSINESS_CARD] @PROCESS_ID";
        public const string USP_MERGE_BUSINESS_CARD = "dbo.USP_MERGE_BUSINESS_CARD @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @ENG_NAME, @ENG_TITLE, @ENG_DIVISION_CODE, @ENG_DIVISION_NAME, @ENG_DEPARTMENT, @KOR_NAME, @KOR_TITLE, @KOR_TITLE_NAME, @KOR_DIVISION_CODE, @KOR_DIVISION_NAME, @KOR_DEPARTMENT, @TEL_OFFICE, @MOBILE, @FAX, @E_MAIL, @ADDRESS_CODE, @ADDRESS, @QUANTITY, @KOR_JOB_TITLE, @COLOR_CODE, @IS_DISUSED, @CREATOR_ID";
        public const string USP_SELECT_BUSINESS_CARD_DISPLAY_NAME_CARD = "dbo.USP_SELECT_BUSINESS_CARD_DISPLAY_NAME_CARD @PROCESS_ID";
        public const string USP_SELECT_BUSINESS_CARD_AGENCY = "[dbo].[USP_SELECT_BUSINESS_CARD_AGENCY] @PROCESS_ID";
        #endregion

        #region [ 3. Collateral Management ]

        public const string USP_MERGE_MORTGAGE_MANAGMENT = "[dbo].[USP_MERGE_MORTGAGE_MANAGEMENT] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @CUSTOMER_CODE, @CUSTOMER_NAME, @STATUS_CODE, @BG_CODE, @MORTGAGE_TYPE, @BOOK_VALUE, @REVALUTION_VALUE, @NEW_CREDIT_LIMIT, @RECEIVED_DATE, @RETURN_DATE, @ISSUE_DATE, @DUE_DATE, @PUBLISHER, @PUBLISHED_NUM, @CREDIT_LIMIT, @CURRENTLY_PROCESS_ID, @COMMENT, @APPLY_MASTER, @IS_DISUSED, @CREATOR_ID";

        public const string USP_SELECT_MORTGAGE_MANAGMENT = "[dbo].[USP_SELECT_MORTGAGE_MANAGEMENT] @PROCESS_ID";

        public const string USP_SELECT_NEW_CREDIT_LIMIT = "[dbo].[USP_SELECT_NEW_CREDIT_LIMIT] @CUSTOMER_CODE, @BG_CODE, @STATUS_CODE, @INPUT_AMOUNT";

        public const string USP_UPDATE_MORTGAGE_MANAGEMENT_CREDIT_LIMIT = "[dbo].[USP_UPDATE_MORTGAGE_MANAGEMENT_CREDIT_LIMIT] @PROCESS_ID, @CREDIT_LIMIT_STATUS, @UPDATER_ID, @CURRENTLY_PROCESS_ID";

        public const string USP_UPDATE_CREDIT_LIMIT = "[eManage].[dbo].[USP_UPDATE_CREDIT_LIMIT] @CUSTOMER_CODE, @BU, @CREDIT_LIMIT ";

        public const string USP_SELECT_COLLATERAL_BG = "[dbo].[USP_SELECT_COLLATERAL_BG]";
        #endregion

        #region [ 4. Credit Note ]

        public const string USP_MERGE_CREDIT_DEBIT_NOTE = "[dbo].[USP_MERGE_CREDIT_DEBIT_NOTE] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @TO_CODE, @TO_NAME, @COMPANY_ID, @INVOICE_DATE, @DUE_DATE, @CURRENCY, @TOTAL_AMOUNT, @LOCAL_AMOUNT, @DESCRIPTION, @IS_DISUSED, @CREATOR_ID";

        public const string USP_MERGE_CREDIT_DEBIT_NOTE_ATTN = "[dbo].[USP_MERGE_CREDIT_DEBIT_NOTE_ATTN] @PROCESS_ID, @ATTN_CODE, @ATTN_NAME, @ATTN_MAIL_ADDRESS, @ATTN_TYPE, @CREATOR_ID";

        public const string USP_MERGE_CREDIT_DEBIT_NOTE_CC = "[dbo].[USP_MERGE_CREDIT_DEBIT_NOTE_CC] @PROCESS_ID, @CC_CODE, @CC_NAME, @CC_MAIL_ADDRESS, @CC_TYPE, @CREATOR_ID";

        public const string USP_MERGE_CREDIT_DEBIT_NOTE_DESC = "[dbo].[USP_MERGE_CREDIT_DEBIT_NOTE_DESC] @PROCESS_ID, @IDX, @DESCRIPTION, @AMOUNT, @CREATOR_ID";

        public const string USP_SELECT_CREDIT_DEBIT_NOTE = "[dbo].[USP_SELECT_CREDIT_DEBIT_NOTE] @PROCESS_ID";

        public const string USP_SELECT_CREDIT_DEBIT_NOTE_ATTN = "[dbo].[USP_SELECT_CREDIT_DEBIT_NOTE_ATTN] @PROCESS_ID";

        public const string USP_SELECT_CREDIT_DEBIT_NOTE_CC = "[dbo].[USP_SELECT_CREDIT_DEBIT_NOTE_CC] @PROCESS_ID";

        public const string USP_SELECT_CREDIT_DEBIT_NOTE_DESC = "[dbo].[USP_SELECT_CREDIT_DEBIT_NOTE_DESC] @PROCESS_ID";

        public const string USP_DELETE_CREDIT_DEBIT_NOTE_ATTN = "[dbo].[USP_DELETE_CREDIT_DEBIT_NOTE_ATTN] @PROCESS_ID";

        public const string USP_DELETE_CREDIT_DEBIT_NOTE_CC = "[dbo].[USP_DELETE_CREDIT_DEBIT_NOTE_CC] @PROCESS_ID";

        public const string USP_DELETE_CREDIT_DEBIT_NOTE_DESC_IDX = "[dbo].[USP_DELETE_CREDIT_DEBIT_NOTE_DESC_IDX] @PROCESS_ID, @IDX";

        public const string USP_SELECT_CREDIT_DEBIT_NOTE_VIEW = "[dbo].[USP_SELECT_CREDIT_DEBIT_NOTE_VIEW] @PROCESS_ID";

        public const string USP_SELECT_PROCESS_RECIPIENT_LIST = "[dbo].[USP_SELECT_PROCESS_RECIPIENT_LIST] @PROCESS_ID";

        #endregion

        #region [ 5. Debit Note ]

        #endregion

        #region [ 6. Credit & Debit Memo ]

        public const string USP_MERGE_CREDIT_DEBIT_MEMO = "[dbo].[USP_MERGE_CREDIT_DEBIT_MEMO] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE_CODE, @PURPOSE_CODE, @BU, @ADJUST_AMOUNT, @REASON_DESC, @IS_DISUSED, @CREATOR_ID";

        public const string USP_MERGE_CREDIT_DEBIT_MEMO_PRODUCT = "[dbo].[USP_MERGE_CREDIT_DEBIT_MEMO_PRODUCT] @PROCESS_ID, @PRODUCT_CODE, @PRODUCT_NAME, @CREATOR_ID";

        public const string USP_MERGE_CREDIT_DEBIT_MEMO_WHOLESALER = "[dbo].[USP_MERGE_CREDIT_DEBIT_MEMO_WHOLESALER] @PROCESS_ID, @WHOLESALER_CODE, @WHOLESALER_NAME, @CREATOR_ID";

        public const string USP_DELETE_CREDIT_DEBIT_MEMO_PRODUCT_ALL = "[dbo].[USP_DELETE_CREDIT_DEBIT_MEMO_PRODUCT_ALL] @PROCESS_ID";

        public const string USP_DELETE_CREDIT_DEBIT_MEMO_WHOLESALER_ALL = "[dbo].[USP_DELETE_CREDIT_DEBIT_MEMO_WHOLESALER_ALL] @PROCESS_ID";

        public const string USP_SELECT_CREDIT_DEBIT_MEMO = "[dbo].[USP_SELECT_CREDIT_DEBIT_MEMO] @PROCESS_ID";

        public const string USP_SELECT_CREDIT_DEBIT_MEMO_PRODUCT = "[dbo].[USP_SELECT_CREDIT_DEBIT_MEMO_PRODUCT] @PROCESS_ID";

        public const string USP_SELECT_CREDIT_DEBIT_MEMO_WHOLESALER = "[dbo].[USP_SELECT_CREDIT_DEBIT_MEMO_WHOLESALER] @PROCESS_ID";


        #endregion

        #region [ 7. Credit Limit Setting ]

        public const string USP_SELECT_CREDIT_LIMIT_SETTING = "dbo.USP_SELECT_CREDIT_LIMIT_SETTING @PROCESS_ID";
        //eWorkflow Optimization 2020
        public const string USP_MERGE_CREDIT_LIMIT_SETTING = "dbo.USP_MERGE_CREDIT_LIMIT_SETTING @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @IS_ALL, @BU, @BUSINESS_GROUP,@TYPE, @CATEGORY, @CUSTOMER_CODE, @CUSTOMER_NAME, @AMOUNT, @DESCRIPTION, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";


        #endregion

        #region [ 8. Credit Release ]

        public const string USP_SELECT_CREDIT_RELEASE = "dbo.USP_SELECT_CREDIT_RELEASE @PROCESS_ID";
        public const string USP_MERGE_CREDIT_RELEASE = "dbo.USP_MERGE_CREDIT_RELEASE @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @ORDER_NUM, @BU, @CUSTOMER_CODE, @CUSTOMER_NAME, @AMOUNT, @INCL_NOTE_AMOUNT, @PAYMENT_TERM, @AGING_DAY, @OVERDUE, @CREDIT_LIMIT,@OPEN_ORDER, @ORDERED_AMOUNT, @EXCEEDED_AMOUNT, @COLLATERAL_AMOUNT, @REASON, @EXPLANATION_OF_REASON, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        #endregion

        #region [ 9. Special Pricing ]

        public const string USP_MERGE_SPECIAL_PRICING = "[dbo].[USP_MERGE_SPECIAL_PRICING] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @IS_ALL_CUSTOMER, @CUSTOMER_CODE, @CUSTOMER_NAME, @PERIOD, @ENFORCEMENT_DATE, @REASON, @IS_DISUSED, @CREATOR_ID";

        public const string USP_MERGE_SPECIAL_PRICING_PRODUCT = "[dbo].[USP_MERGE_SPECIAL_PRICING_PRODUCT] @PROCESS_ID, @PRODUCT_CODE, @PRODUCT_NAME, @PRICE_BEFORE, @ORDER_QTY, @PRICE_AFTER, @DC, @TOTAL_SALES, @TOTAL_DC, @REQUEST_DATE, @REQUEST_QTY, @REQUEST_PRICE, @CREATOR_ID";

        public const string USP_DELETE_SPECIAL_PRICING_PRODUCT = "[dbo].[USP_DELETE_SPECIAL_PRICING_PRODUCT] @PROCESS_ID, @PRODUCT_CODE";

        public const string USP_SELECT_SPECIAL_PRICING = "[dbo].[USP_SELECT_SPECIAL_PRICING] @PROCESS_ID";

        public const string USP_SELECT_SPECIAL_PRICING_PRODUCT = "[dbo].[USP_SELECT_SPECIAL_PRICING_PRODUCT] @PROCESS_ID";

        #endregion

        #region [ 10. Base Price ]
        public const string USP_INSERT_BASE_PRICE_PRODUCT = "[dbo].[USP_INSERT_BASE_PRICE_PRODUCT] @PROCESS_ID, @PRODUCT_CODE, @PRODUCT_NAME, @CURRENT_PRICE, @CURRENT_PRICE_INCLUDE_VAT, @BASE_PRICE, @REVISED_PRICE_INCLUDE_VAT, @REVISED_PRICE_EXCLUDE_VAT, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_MERGE_BASE_PRICE = "[dbo].[USP_MERGE_BASE_PRICE] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @CATEGORY, @BU, @DESCRIPTION, @CONTRACT_PERIOD, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_SELECT_BASE_PRICE = "[dbo].[USP_SELECT_BASE_PRICE] @PROCESS_ID";

        public const string USP_SELECT_BASE_PRICE_PRODUCT = "[dbo].[USP_SELECT_BASE_PRICE_PRODUCT] @PROCESS_ID";

        public const string USP_DELETE_BASE_PRICE_PRODUCT = "[DBO].[USP_DELETE_BASE_PRICE_PRODUCT] @PROCESS_ID, @PRODUCT_CODE";

        public const string USP_DELETE_BASE_PRICE_PRODUCT_ALL = "[DBO].[USP_DELETE_BASE_PRICE_PRODUCT_ALL] @PROCESS_ID";
        #endregion

        #region [ 11. Free Goods ]

        public const string USP_MERGE_FREE_GOODS = "[dbo].[USP_MERGE_FREE_GOODS] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @LOCATION, @TITLE_CODE, @PURPOSE_CODE, @D_BOX, @PO_NO, @COMMENT, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE ";

        public const string USP_INSERT_FREE_GOODS_INFO = "[dbo].[USP_INSERT_FREE_GOODS_INFO] @PROCESS_ID, @IDX, @IS_DOCTOR_PHARMACY, @INSTITUE_CODE, @INSTITUE_NAME, @HCP_CODE, @HCP_NAME, @SPECIALTY_CODE, @SPECIALTY_NAME, @SAMPLE_CODE, @SAMPLE_NAME, @QTY, @PURPOSE, @SAP_PRODUCT_CODE, @STATES, @OLD_DOC_NUMBER, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_INSERT_FREE_GOODS_CUSTOMER = "[dbo].[USP_INSERT_FREE_GOODS_CUSTOMER] @PROCESS_ID, @IDX, @CUSTOMER, @RECEIPTER, @SAMPLE_CODE, @SAMPLE_NAME, @QTY,@PURPOSE, @SAP_PRODUCT_CODE, @STATES, @OLD_DOC_NUMBER, @CREATOR_ID, @CREATE_DATE";

        public const string USP_SELECT_FREE_GOODS = "[dbo].[USP_SELECT_FREE_GOODS] @PROCESS_ID";

        public const string USP_SELECT_FREE_GOODS_INFO = "[dbo].[USP_SELECT_FREE_GOODS_INFO] @PROCESS_ID";

        public const string USP_SELECT_FREE_GOODS_CUSTOMER = "[dbo].[USP_SELECT_FREE_GOODS_CUSTOMER] @PROCESS_ID";

        public const string USP_DELETE_FREE_GOODS_INFO = "[dbo].[USP_DELETE_FREE_GOODS_INFO] @PROCESS_ID, @IDX";

        public const string USP_DELETE_FREE_GOODS_INFO_ALL = "[dbo].[USP_DELETE_FREE_GOODS_INFO_ALL] @PROCESS_ID";

        public const string USP_DELETE_FREE_GOODS_CUSTOMER = "[dbo].[USP_DELETE_FREE_GOODS_CUSTOMER] @PROCESS_ID, @IDX";

        public const string USP_DELETE_FREE_GOODS_CUSTOMER_ALL = "[dbo].[USP_DELETE_FREE_GOODS_CUSTOMER_ALL] @PROCESS_ID";

        public const string USP_DELETE_FREE_GOODS_CHECK_DUPLICATE = "[dbo].[USP_DELETE_FREE_GOODS_CHECK_DUPLICATE] @USER_ID";

        public const string USP_INSERT_FREE_GOODS_CHECK_DUPLICATE = "[dbo].[USP_INSERT_FREE_GOODS_CHECK_DUPLICATE] @USER_ID, @PURPOSE_CODE, @BU, @INSTITUE_CODE, @INSTITUE_NAME, @HCP_CODE, @HCP_NAME, @SAP_PRODUCT_CODE, @CREATE_DATE";

        public const string USP_SELECT_FREE_GOODS_DUPLICATE = "[dbo].[USP_SELECT_FREE_GOODS_DUPLICATE] @USER_ID, @PURPOSE_CODE, @BU";
        #endregion

        #region [ 12. WholeSaler Margin Agreement ]

        public const string USP_MERGE_WHOLESALER_MARGIN_AGREEMENT = "[dbo].[USP_MERGE_WHOLESALER_MARGIN_AGREEMENT] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @BU, @CHECK_CONFIG, @WHOLESALER_CODE, @WHOLESALER_NAME, @CONTRACT_FROM, @CONTRACT_TO, @TOTAL_AMOUNT, @IS_DISUSED, @CREATOR_ID";

        public const string USP_MERGE_WHOLESALER_MARGIN_AGREEMENT_CUSTOMER = "[dbo].[USP_MERGE_WHOLESALER_MARGIN_AGREEMENT_CUSTOMER] @PROCESS_ID, @CUSTOMER_CODE, @CUSTOMER_NAME, @CREATOR_ID";

        public const string USP_MERGE_WHOLESALER_MARGIN_AGREEMENT_HOSPITAL = "[dbo].[USP_MERGE_WHOLESALER_MARGIN_AGREEMENT_HOSPITAL] @PROCESS_ID, @HOSPITAL_CODE, @HOSPITAL_NAME, @CREATOR_ID";

        public const string USP_MERGE_WHOLESALER_MARGIN_AGREEMENT_PRODUCT = "[dbo].[USP_MERGE_WHOLESALER_MARGIN_AGREEMENT_PRODUCT] @PROCESS_ID, @IDX, @PRODUCT_CODE, @PRODUCT_NAME, @BASE_PRICE, @MARGIN_AS_IS, @MARGIN_TO_BE, @DISCOUNT_AMOUNT, @QTY, @AMOUNT, @REMARKS, @CREATOR_ID";

        public const string USP_DELETE_WHOLESALER_MARGIN_AGREEMENT_PRODUCT = "[dbo].[USP_DELETE_WHOLESALER_MARGIN_AGREEMENT_PRODUCT] @PROCESS_ID, @IDX";

        public const string USP_DELETE_WHOLESALER_MARGIN_AGREEMENT_CUSTOMER_ALL = "[dbo].[USP_DELETE_WHOLESALER_MARGIN_AGREEMENT_CUSTOMER_ALL] @PROCESS_ID";

        public const string USP_DELETE_WHOLESALER_MARGIN_AGREEMENT_HOSPITAL_ALL = "[dbo].[USP_DELETE_WHOLESALER_MARGIN_AGREEMENT_HOSPITAL_ALL] @PROCESS_ID";

        public const string USP_DELETE_WHOLESALER_MARGIN_AGREEMENT_PRODUCT_ALL = "[dbo].[USP_DELETE_WHOLESALER_MARGIN_AGREEMENT_PRODUCT_ALL] @PROCESS_ID";

        public const string USP_SELECT_WHOLESALER_MARGIN_AGREEMENT = "[dbo].[USP_SELECT_WHOLESALER_MARGIN_AGREEMENT] @PROCESS_ID";

        public const string USP_SELECT_WHOLESALER_MARGIN_AGREEMENT_CUSTOMER = "[dbo].[USP_SELECT_WHOLESALER_MARGIN_AGREEMENT_CUSTOMER] @PROCESS_ID";

        public const string USP_SELECT_WHOLESALER_MARGIN_AGREEMENT_HOSPITAL = "[dbo].[USP_SELECT_WHOLESALER_MARGIN_AGREEMENT_HOSPITAL] @PROCESS_ID";

        public const string USP_SELECT_WHOLESALER_MARGIN_AGREEMENT_PRODUCT = "[dbo].[USP_SELECT_WHOLESALER_MARGIN_AGREEMENT_PRODUCT] @PROCESS_ID";

        #endregion

        #region [ 13. Incentive Scheme ]

        public const string USP_MERGE_INCENTIVE_SCHEME = "dbo.USP_MERGE_INCENTIVE_SCHEME @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE, @BU, @PROGRAM, @SETTLEMENT_TYPE, @DESCRIPTION, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE ";
        public const string USP_SELECT_INCENTIVE_SCHEME = "dbo.USP_SELECT_INCENTIVE_SCHEME @PROCESS_ID ";

        #endregion

        #region [ 14. Incentive Payment ]
        public const string USP_MERGE_INCENTIVE_PAYMENT = "dbo.USP_MERGE_INCENTIVE_PAYMENT @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @SCHEME_DOC_NUM, @TOTAL_AMOUNT, @DEALERS_NUM, @PAYMENT_DATE, @PAYMENT_SYSTEM, @PAY_TO, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE, @REMARK,@SETTLEMENT_TYPE";
        public const string USP_SELECT_INCENTIVE_PAYMENT = "[dbo].[USP_SELECT_INCENTIVE_PAYMENT] @PROCESS_ID";
        public const string USP_SELECT_INCENTIVE_PAYMENT_I = "[dbo].[USP_SELECT_INCENTIVE_PAYMENT_I] @PROCESS_ID";
        #endregion

        #region [ 15. Early Payment ]

        public const string USP_MERGE_EARLY_PAYMENT_DISCOUNT = "[dbo].[USP_MERGE_EARLY_PAYMENT_DISCOUNT] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TOTAL_AMOUNT, @DEALERS_NUM, @PAYMENT_DATE, @IS_DISUSED, @CREATOR_ID";

        public const string USP_SELECT_EARLY_PAYMENT_DISCOUNT = "[dbo].[USP_SELECT_EARLY_PAYMENT_DISCOUNT] @PROCESS_ID";

        #endregion

        #region [ 16. Membership Application ]

        public const string USP_MERGE_MEMBERSHIP_APPLICATION = "[dbo].[USP_MERGE_MEMBERSHIP_APPLICATION] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TA_CATEGORY, @ENG_NAME, @KOR_NAME, @OBJECTIVE, @PURPOSE, @PRESIDENT_SECRETARY, @MEMBERSHIP_FEE, @ADDRESS, @PHONE_NO, @FAX, @HOMEPAGE, @RELEVANT_BUSINESS, @JOB_FUNCTION, @SUB_COMMITTE, @IS_DISUSED, @CREATOR_ID";

        public const string USP_SELECT_MEMBERSHIP_APPLICATION = "[dbo].[USP_SELECT_MEMBERSHIP_APPLICATION] @PROCESS_ID";

        #endregion

        #region [ 17. Competitor Contract ]

        public const string USP_MERGE_COMPETITOR_CONTRACT = "[dbo].[USP_MERGE_COMPETITOR_CONTRACT] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @CATEGORY_CODE, @TA_CATEGORY, @HOST_CODE, @MEETING_DATETIME, @FROM_TIME, @TO_TIME, @VENUE, @AGENDA, @COUNTER_PARTY, @CONTRACT_NUM, @CONTRACT_PERIOD, @PRODUCT, @ACTIVITY, @PURPOSE_CODE, @OTHER_PURPOSE, @EXTERNAL_PARTICIPANTS, @IS_DISUSED, @CREATOR_ID";

        public const string USP_MERGE_COMPETITOR_CONTRACT_PARTICIPANTS = "[dbo].[USP_MERGE_COMPETITOR_CONTRACT_PARTICIPANTS] @PROCESS_ID, @PARTICIPANT_CODE, @PARTICIPANT_NAME, @PARTICIPANT_TYPE, @CREATOR_ID";

        public const string USP_DELETE_COMPETITOR_CONTRACT_PARTICIPANTS = "[dbo].[USP_DELETE_COMPETITOR_CONTRACT_PARTICIPANTS] @PROCESS_ID";

        public const string USP_SELECT_COMPETITOR_CONTRACT = "[dbo].[USP_SELECT_COMPETITOR_CONTRACT] @PROCESS_ID";

        public const string USP_SELECT_COMPETITOR_CONTRACT_PARTICIPANTS = "[dbo].[USP_SELECT_COMPETITOR_CONTRACT_PARTICIPANTS] @PROCESS_ID";

        #endregion

        #region [ 18. ReSale Data Collection ]
        //LPC-forMonsanto User
        public const string USP_MERGE_RESALE_DATA_COLLECTION = "[dbo].[USP_MERGE_RESALE_DATA_COLLECTION] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @DATA_SOURCE, @RESALE_DATA_DETAILS, @RESALE_PRICE, @OTHERS,@PRICEVALUE,@EMPLOYEE, @COLLECTION_PURPOSE, @DATA_ARCHIVING, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";
        //LPC-forMonsanto User
        public const string USP_SELECT_RESALE_DATA_COLLECTION = "[dbo].[USP_SELECT_RESALE_DATA_COLLECTION] @PROCESS_ID";
        #endregion

        #region [ 19. Strategic Change Report ]

        public const string USP_MERGE_STRATEGIC_CHANGE_REPORT = "[dbo].[USP_MERGE_STRATEGIC_CHANGE_REPORT] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @STRATEGIC_CHANGE_CODE, @PURPOSE_JUSTIFICATION, @PRODUCT_NAME, @PRE_SALE_QTY, @PRE_PRICE, @NEW_PRICE, @IS_TIE_IN_SALE, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_SELECT_STRATEGIC_CHANGE_REPORT = "[dbo].[USP_SELECT_STRATEGIC_CHANGE_REPORT] @PROCESS_ID";

        #endregion

        #region [ 20. Annual Review Of Market Position ]
        public const string USP_MERGE_MARKET_POSITION_REVIEW = "[dbo].[USP_MERGE_MARKET_POSITION_REVIEW] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @YEAR, @PRODUCT, @APPLICATION_INDICATION, @COMPETITOR, @MARKET_SHARE, @MARKET_SHARE_VOLUME, @MARKET_SHARE_VALUE, @FIRST_MARKET_SHARE, @SECOND_MARKET_SHARE, @THIRD_MARKET_SHARE, @TOTAL_MARKET_SHARE, @FIRST_PRODUCT_COMPANY_NAME, @SECOND_PRODUCT_COMPANY_NAME, @THIRD_PRODUCT_COMPANY_NAME, @DATA_SOURCE, @CHECKED_DISCRIMINATION, @CHECKED_EXCESSIVE_PRICING, @CHECKED_PREDATORY_PRICING, @CHECKED_MARGIN_SQUEEZE, @CHECKED_TRYING_AND_BUNDING, @CHECKED_LOYALTY_AND_DISCOUNT, @CHECKED_ABUSIVE_EXCLUSIVE_DEALING, @CHECKED_ABUSIVE_REFUSAL_TO_SUPPLY, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE ";

        public const string USP_SELECT_MARKET_POSITION_REVIEW = "[dbo].[USP_SELECT_MARKET_POSITION_REVIEW] @PROCESS_ID";

        #endregion

        #region [ 21. Secondary Seal ]
        public const string USP_MERGE_SECONDARY_SEAL = "[dbo].[USP_MERGE_SECONDARY_SEAL] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @SEAL_TYPE,@SEAL_COMPANY,@SIGN_TYPE, @SEAL_HOLDER_CODE, @RECIPIENT, @PURPOSE_DETAILS, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_SELECT_SECONDARY_SEAL = "[dbo].[USP_SELECT_SECONDARY_SEAL] @PROCESS_ID";
        #endregion

        #region [ 22. Sample Request ]

        public const string USP_MERGE_SAMPLE_REQUEST = "dbo.USP_MERGE_SAMPLE_REQUEST @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @CATEGORY_CODE, @PURPOSE, @TOTAL_AMOUNT, @TO_ADDRESS, @DIRECT_TO_ADDRESS, @DIRECT_TO_PHONE, @RELEVANT_E_WORKFLOW_NO, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";
        public const string USP_MERGE_SAMPLE_REQUEST_ITEMS = "dbo.USP_MERGE_SAMPLE_REQUEST_ITEMS @PROCESS_ID, @IDX, @ITEM_CODE, @ITEM_DESC, @QTY, @PRICE, @AMOUNT, @COST_CODE, @COST_NAME, @LOCATION_CODE, @LOCATION_NAME, @SAP_QTY, @SAP_ORDER_NUM, @REMARK, @CREATOR_ID, @CREATE_DATE";
        public const string USP_SELECT_SAMPLE_REQUEST = "dbo.USP_SELECT_SAMPLE_REQUEST @PROCESS_ID";
        public const string USP_SELECT_SAMPLE_REQUEST_ITEMS = "dbo.USP_SELECT_SAMPLE_REQUEST_ITEMS @PROCESS_ID";
        public const string USP_DELETE_SAMPLE_REQUEST_ITEMS_ALL = "dbo.USP_DELETE_SAMPLE_REQUEST_ITEMS_ALL @PROCESS_ID";
        public const string USP_DELETE_SAMPLE_REQUEST_ITEMS = "dbo.USP_DELETE_SAMPLE_REQUEST_ITEMS @PROCESS_ID, @IDX";

        #endregion

        #region [ 23. Return Goods ]

        public const string USP_SELECT_BCS_RETURN_GOODS = "dbo.USP_SELECT_BCS_RETURN_GOODS @PROCESS_ID";

        public const string USP_SELECT_BCS_RETURN_GOODS_LIST = "dbo.USP_SELECT_BCS_RETURN_GOODS_LIST @PROCESS_ID";

        public const string USP_MERGE_BCS_RETURN_GOODS = "dbo.USP_MERGE_BCS_RETURN_GOODS @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BG, @DISTRIBUTION, @TYPE, @REASON, @REMARK, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";

        public const string USP_MERGE_BCS_RETURN_GOODS_LIST = "dbo.USP_MERGE_BCS_RETURN_GOODS_LIST @PROCESS_ID, @IDX, @CUSTOMER_CODE, @CUSTOMER_NAME,@CUSTOMER_NAME_NEW, @CUR_PRODUCT_CODE, @CUR_PRODUCT_NAME, @CUR_QTY, @CUR_REASON, @CUR_UNIT_PRICE, @CUR_AMOUNT, @REP_PRODUCT_CODE, @REP_PRODUCT_NAME, @REP_QTY, @REP_REASON, @REP_UNIT_PRICE, @REP_AMOUNT,@RETURN_PRICE,@RETURN_PRICE_NEW, @DIFFERENCE,@TOTAL_AMOUNT,@CREATOR_ID, @CREATE_DATE";

        public const string USP_DELETE_BCS_RETURN_GOODS_LIST = "dbo.USP_DELETE_BCS_RETURN_GOODS_LIST @PROCESS_ID, @IDX";

        public const string USP_DELETE_BCS_RETURN_GOODS_LIST_ALL = "dbo.USP_DELETE_BCS_RETURN_GOODS_LIST_ALL @PROCESS_ID";

        #endregion

        #region [ 24. Refund Request ]

        #endregion

        #region [ 25. Price Creating Change ]

        #endregion

        #region [ 26. P&I Plan ]

        #endregion

        #region [ 27. P&I Activity ]
        //eWorkflow Optimization 2020
        public const string USP_MERGE_P_I_ACTIVITY = "[dbo].[USP_MERGE_P_I_ACTIVITY] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE, @BU,@REQUEST_TYPE, @ACTIVITY_TYPE, @INCENTIVE_AGREEMENT, @INCENTIVE_CHECKLIST, @COST_CENTER, @MEETING_VENUE, @FROM_DATE, @TO_DATE, @ADDRESS_VENUE, @PURPOSE, @RELEVANT_E_WORKFLOW_NO, @GO_NUM, @NON_GO_NUM, @FARMER_NUM, @BAYER_EMPLOYEE_NUM, @TOTAL_AMOUNT, @IS_DISUSED, @CREATOR_ID, @EXISTS_PROMOTIONAL";
        //eWorkflow Optimization 2020
        public const string USP_INSERT_P_I_ACTIVITY_COST_DETAIL = "[dbo].[USP_INSERT_P_I_ACTIVITY_COST_DETAIL] @PROCESS_ID, @IDX, @CATEGORY_CODE, @CATEGORY_NAME, @DESCRIPTION, @QTY, @UNIT_PRICE, @AMOUNT, @CREATOR_ID";

        public const string USP_DELETE_P_I_ACTIVITY_COST_DETAIL_ALL = "[dbo].[USP_DELETE_P_I_ACTIVITY_COST_DETAIL_ALL] @PROCESS_ID";

        public const string USP_DELETE_P_I_ACTIVITY_COST_DETAIL = "[dbo].[USP_DELETE_P_I_ACTIVITY_COST_DETAIL] @PROCESS_ID, @IDX";

        public const string USP_SELECT_P_I_ACTIVITY = "[dbo].[USP_SELECT_P_I_ACTIVITY] @PROCESS_ID";

        public const string USP_SELECT_P_I_ACTIVITY_COST_DETAIL = "[dbo].[USP_SELECT_P_I_ACTIVITY_COST_DETAIL] @PROCESS_ID";
        #endregion

        #region [ 28. Cancelation Mortgage ]

        public const string USP_MERGE_CANCELATION_MORTGAGE = "[dbo].[USP_MERGE_CANCELATION_MORTGAGE] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @TYPE, @CUSTOMER_CODE, @CUSTOMER_NAME, @REASON, @MORTGAGE, @MORTGAGE_AMOUNT, @IS_DISUSED, @CREATOR_ID";

        public const string USP_SELECT_CANCELATION_MORTGAGE = "[dbo].[USP_SELECT_CANCELATION_MORTGAGE] @PROCESS_ID";

        #endregion

        #region [ 29. Claim Settlement Proposal ]

        public const string USP_SELECT_CLAIM_SETTLEMENT = "dbo.USP_SELECT_CLAIM_SETTLEMENT @PROCESS_ID";
        public const string USP_SELECT_CLAIM_SETTLEMENT_LIST = "dbo.USP_SELECT_CLAIM_SETTLEMENT_LIST @PROCESS_ID";

        public const string USP_MERGE_CLAIM_SETTLEMENT_LIST = "dbo.USP_MERGE_CLAIM_SETTLEMENT_LIST @PROCESS_ID, @IDX, @NAME, @AMOUNT, @REASON, @BANK_ACCOUNT, @PRODUCT_CODE, @PRODUCT_NAME, @QTY, @CREATOR_ID, @CREATE_DATE";
        public const string USP_MERGE_CLAIM_SETTLEMENT = "dbo.USP_MERGE_CLAIM_SETTLEMENT @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";

        public const string USP_DELETE_CLAIM_SETTLEMENT_LIST_ALL = "dbo.USP_DELETE_CLAIM_SETTLEMENT_LIST_ALL @PROCESS_ID";
        public const string USP_DELETE_CLAIM_SETTLEMENT_LIST_IDX = "dbo.USP_DELETE_CLAIM_SETTLEMENT_LIST_IDX @PROCESS_ID, @IDX";

        #endregion

        #region [ 30. Active Toll Contract ]

        #endregion

        #region [ 31. Coporate Card ]
        public const string USP_MERGE_CORPORATE_CARD = "dbo.USP_MERGE_CORPORATE_CARD @PROCESS_ID,@SUBJECT,@DOC_NUM,@PROCESS_STATUS,@REQUESTER_ID,@REQUEST_DATE,@COMPANY_CODE,@ORGANIZATION_NAME,@LIFE_CYCLE,@CATEGORY_CODE,@BIRTHDAY,@REASON,@CARD_NUMBER,@PERIOD_FOR_INCREASE_CODE,@STARTING_DATE,@PERIOD,@INCREASE_AMOUNT,@REASON_CODE,@REASON_OTHERS,@CHANGEMENT_ITEM,@BANK_NAME,@BANK_ACOUNT_NUMBER,@CELL_PHONE_NUMBER,@ADDRESS,@NAME,@NEW_PASSWORD,@IS_DISUSED,@CREATOR_ID,@CREATE_DATE,@UPDATER_ID,@UPDATE_DATE";

        public const string USP_SELECT_CORPORATE_CARD = "dbo.USP_SELECT_CORPORATE_CARD @PROCESS_ID";
        #endregion

        #region [ 32. Material Price Create&Change ]

        public const string USP_MERGE_MATERIAL_PRICE = "[dbo].[USP_MERGE_MATERIAL_PRICE] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @CATEGORY_CODE, @PURPOSE_CODE, @MATERIAL_TYPE, @PRODUCT, @K_REACH_VERIFICATION, @COUNTER_MESSAGE,  @SUPPLIER_NUMBER, @SUPPLIER_NAME, @INCOTERMS, @PAYMENT_TERMS, @REMARK, @IS_SECONDARY_SEAL, @IS_DISUSED, @CREATOR_ID ";

        public const string USP_DELETE_MATERIAL_PRICE_LIST = "[dbo].[USP_DELETE_MATERIAL_PRICE_LIST] @PROCESS_ID, @IDX";

        public const string USP_DELETE_MATERIAL_PRICE_LIST_ALL = "[dbo].[USP_DELETE_MATERIAL_PRICE_LIST_ALL] @PROCESS_ID ";

        public const string USP_DELETE_MATERIAL_PRICE_PRODUCT_ALL = "[dbo].[USP_DELETE_MATERIAL_PRICE_PRODUCT_ALL] @PROCESS_ID";
        
        public const string USP_INSERT_MATERIAL_PRICE_LIST = "[dbo].[USP_INSERT_MATERIAL_PRICE_LIST] @PROCESS_ID, @IDX, @MATERIAL_CODE, @MATERIAL_NAME, @CURRENCY, @UNIT_PRICE, @TO_BE_UNIT_PRICE, @MANUFACTURER, @CREATOR_ID ";

        public const string USP_SELECT_MATERIAL_PRICE = "[dbo].[USP_SELECT_MATERIAL_PRICE] @PROCESS_ID ";

        public const string USP_SELECT_MATERIAL_PRICE_LIST = "[dbo].[USP_SELECT_MATERIAL_PRICE_LIST] @PROCESS_ID ";

        public const string USP_SELECT_MATERIAL_PRICE_PRODUCT = "[dbo].[USP_SELECT_MATERIAL_PRICE_PRODUCT] @PROCESS_ID";

        public const string USP_MERGE_MATERIAL_PRICE_PRODUCT = "[dbo].[USP_MERGE_MATERIAL_PRICE_PRODUCT] @PROCESS_ID, @PRODUCT_CODE, @PRODUCT_NAME, @CREATOR_ID";

        #endregion

        #region [ 33. Rebate Policy & Invoice price ]

        public const string USP_MERGE_REBATE_POLICY = "[dbo].[USP_MERGE_REBATE_POLICY] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BG, @DISTRIBUTION, @TYPE,@CUSTOMER,@TOTAL_AMOUNT, @START_DATE, @REMARK, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_INSERT_REBATE_POLICY_PRODUCT = "[dbo].[USP_INSERT_REBATE_POLICY_PRODUCT] @PROCESS_ID, @AS_IS_PRODUCT_CODE, @AS_IS_PRODUCT_NAME, @AS_IS_CHANNEL_CODE, @AS_IS_CHANNEL_NAME, @AS_IS_DISTRIBUTION, @AS_IS_LIST, @AS_IS_INVOICE, @AS_IS_NET1, @AS_IS_NET2, @TO_BE_PRODUCT_CODE, @TO_BE_PRODUCT_NAME, @TO_BE_CHANNEL_CODE, @TO_BE_CHANNEL_NAME, @TO_BE_DISTRIBUTION, @TO_BE_LIST, @TO_BE_INVOICE, @TO_BE_NET1, @TO_BE_NET2, @CREATOR_ID";

        public const string USP_SELECT_REBATE_POLICY = "[dbo].[USP_SELECT_REBATE_POLICY] @PROCESS_ID";

        public const string USP_SELECT_REBATE_POLICY_PRODUCT = "[dbo].[USP_SELECT_REBATE_POLICY_PRODUCT] @PROCESS_ID";
                
        public const string USP_DELETE_REBATE_POLICY_PRODUCT = "[dbo].[USP_DELETE_REBATE_POLICY_PRODUCT] @PROCESS_ID, @PRODUCT_CODE";
               

        public const string USP_DELETE_REBATE_POLICY_PRODUCT_ALL = "[dbo].[USP_DELETE_REBATE_POLICY_PRODUCT_ALL] @PROCESS_ID";

        //eWorkflow Optimization 2020 
        public const string USP_DELETE_REBATE_POLICY_PRODUCT_NEW = "[dbo].[USP_DELETE_REBATE_POLICY_PRODUCT_NEW] @PROCESS_ID, @PRODUCT_CODE";

        public const string USP_SELECT_REBATE_POLICY_PRODUCT_NEW = "[dbo].[USP_SELECT_REBATE_POLICY_PRODUCT_NEW] @PROCESS_ID";

        public const string USP_DELETE_REBATE_POLICY_PRODUCT_ALL_NEW = "[dbo].[USP_DELETE_REBATE_POLICY_PRODUCT_ALL_NEW] @PROCESS_ID";

        public const string USP_INSERT_REBATE_POLICY_PRODUCT_NEW = "[dbo].[USP_INSERT_REBATE_POLICY_PRODUCT_NEW] @PROCESS_ID , @PRODUCT_CODE, @PRODUCT_NAME, @LIST_PRICE, @LIST_PRICE_NEW, @INVOICE_PRICE, @INVOICE_PRICE_NEW,@NET_PRICE_NEW, @SELLING_DIFF, @SELLING_EXPECTED, @SELLING_TOTAL, @RETURN_PRICE, @RETURN_PRICE_NEW, @RETURN_DIFF, @RETURN_EXPECTED, @RETURN_TOTAL, @CREATOR_ID";       
            #endregion       
#region [ 34. Medical Event _Interactions with Healthcare Professionals ]

        public const string USP_MERGE_INTERACTION_HEALTHCARE_PRO = "[dbo].[USP_MERGE_INTERACTION_HEALTHCARE_PRO] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID"
                                                                + ", @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE, @ACTIVITY_CODE, @FROM_EVENT_DATE, @TO_EVENT_DATE"
                                                                + ", @MEETING_VENUE, @ADDRESS_OF_VENUE, @VENUE_SELECTION_REASON, @VENUE_SELECTION_REASON_ETC, @COMPOUNT_STUDY_NUM"
                                                                + ", @SPONSOR_OF_STUDY, @CRO_NAME, @OBJECTIVE, @IS_INVESTIGATOR_MEETING, @IS_MONITORING_MEETING, @OTHER_SPECIFY"
                                                                + ", @IS_CONTRACT, @PURPOSE_OBJECT, @SCIENTIFIC_MATERIAL, @TARGET_PARTICIPANTS, @GO_NUM, @NON_GO_NUM, @PRIVATE_NUM"
                                                                + ", @FOREIGN_NUM, @BAYER_NUM, @ACCOMMODATION_NEEDED, @EXISTS_EFPIA, @EXISTS_HONORARIUM, @IS_DISUSED, @CREATOR_ID";

        public const string USP_MERGE_INTERACTION_HEALTHCARE_PRO_DETAIL = "[dbo].[USP_MERGE_INTERACTION_HEALTHCARE_PRO_DETAIL] @PROCESS_ID, @IDX, @CATEGORY_CODE, @CATEGORY_NAME, @DESCRIPTION, @QTY, @PRICE, @AMOUNT, @COMMENT, @CREATOR_ID";

        public const string USP_DELETE_INTERACTION_HEALTHCARE_PRO_DETAIL_ALL = "[dbo].[USP_DELETE_INTERACTION_HEALTHCARE_PRO_DETAIL_ALL] @PROCESS_ID";

        public const string USP_DELETE_INTERACTION_HEALTHCARE_PRO_DETAIL = "[dbo].[USP_DELETE_INTERACTION_HEALTHCARE_PRO_DETAIL] @PROCESS_ID, @IDX";

        public const string USP_SELECT_INTERACTION_HEALTHCARE_PRO = "[dbo].[USP_SELECT_INTERACTION_HEALTHCARE_PRO] @PROCESS_ID";

        public const string USP_SELECT_INTERACTION_HEALTHCARE_PRO_DETAIL = "[dbo].[USP_SELECT_INTERACTION_HEALTHCARE_PRO_DETAIL] @PROCESS_ID";

        public const string USP_DELETE_INTERACTION_HEALTHCARE_PRO_COUNTRY_ALL = "[dbo].[USP_DELETE_INTERACTION_HEALTHCARE_PRO_COUNTRY_ALL] @PROCESS_ID";

        public const string USP_MERGE_INTERACTION_HEALTHCARE_PRO_COUNTRY = "[dbo].[USP_MERGE_INTERACTION_HEALTHCARE_PRO_COUNTRY] @PROCESS_ID, @COUNTRY_CODE, @COUNTRY_NAME, @CREATOR_ID";

        public const string USP_SELECT_INTERACTION_HEALTHCARE_PRO_COUNTRY = "[dbo].[USP_SELECT_INTERACTION_HEALTHCARE_PRO_COUNTRY] @PROCESS_ID";


        #endregion

        #region [ 35. Contract Management ]
        
        public const string USP_SELECT_CONTRACT_MANAGEMENT = "dbo.USP_SELECT_CONTRACT_MANAGEMENT @PROCESS_ID";
        public const string USP_MERGE_CONTRACT_MANAGEMENT = "dbo.USP_MERGE_CONTRACT_MANAGEMENT @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @ESSENTIAL_CONTRACT, @INTRAGROUP, @CROSS_BORDER, @CONTRACT_TOTAL_VALUE, @TITLE, @TERM_FROM, @TERM_TO, @CONTRACT_PARTNER, @CONTRACT_VALUE, @CONTRACT_CATEGORY, @PRIVACY_INFORMATION,@PIPA_PURPOSE	, @PIPA_EVENT,@PIPA_CONTRACT,@PIPA_PURPOSE_PI,@PIPA_PURPOSE_PI_OTHER,@PIPA_TARGET,@PIPA_COLLECTION,@PIPA_ARCHIVING,@PIPA_ARCHIVING_OTHER,@PIPA_PERMISSION,@PIPA_VOLUMN,@PIPA_RETENTION,@PIPA_3RDPARTY,@PIPA_OVERSEA, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";

        #endregion

        #region [ 36. Donation ]

        public const string USP_SELECT_DONATION = "dbo.USP_SELECT_DONATION @PROCESS_ID";
        public const string USP_MERGE_DONATION = "dbo.USP_MERGE_DONATION @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @VALUE, @PURPOSE, @EXPLANATION, @RECIPIENT, @ADDRESS, @TELEPHONE, @E_MAIL, @CATEGORY, @PRODUCT_LOCATION, @TOTAL_AMOUNT, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";

        public const string USP_SELECT_DONATION_PRODUCT = "dbo.USP_SELECT_DONATION_PRODUCT @PROCESS_ID";
        public const string USP_MERGE_DONATION_PRODUCT = "dbo.USP_MERGE_DONATION_PRODUCT @PROCESS_ID, @IDX, @BU, @PRODUCT_CODE, @PRODUCT_NAME, @FAIR_MARKET_VALUE, @QTY, @AMOUNT, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";
        public const string USP_DELETE_DONATION_PRODUCT_ALL = "dbo.USP_DELETE_DONATION_PRODUCT_ALL @PROCESS_ID";
        public const string USP_DELETE_DONATION_PRODUCT_IDX = "dbo.USP_DELETE_DONATION_PRODUCT_IDX @PROCESS_ID, @IDX";
        #endregion

        #region [ 37. Return Goods(BHC) ]

        #endregion

        #region [ 38. BASE_PRICE & DISCOUNT]

        public const string USP_SELECT_BASE_DISCOUNT_PRICE = "dbo.USP_SELECT_BASE_DISCOUNT_PRICE @PROCESS_ID";
        public const string USP_MERGE_BASE_DISCOUNT_PRICE = "dbo.USP_MERGE_BASE_DISCOUNT_PRICE @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @CUSTOMER_CODE, @CUSTOMER_NAME, @PRODUCT_TYPE, @DESCRIPTION, @DATE_FROM, @DATE_TO, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";

        public const string USP_SELECT_BASE_DISCOUNT_PRICE_PRODUCT = "dbo.USP_SELECT_BASE_DISCOUNT_PRICE_PRODUCT @PROCESS_ID";
        public const string USP_MERGE_BASE_DISCOUNT_PRICE_PRODUCT = "dbo.USP_MERGE_BASE_DISCOUNT_PRICE_PRODUCT @PROCESS_ID, @IDX, @PRODUCT_CODE, @PRODUCT_NAME, @UNIT, @BASE_PRICE, @BASE_PRICE_TO_BE, @CHANGE_PRICE, @DISCOUNT_PRICE, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";
        public const string USP_DELETE_BASE_DISCOUNT_PRICE_PRODUCT_ALL = "dbo.USP_DELETE_BASE_DISCOUNT_PRICE_PRODUCT_ALL @PROCESS_ID";
        public const string USP_DELETE_BASE_DISCOUNT_PRICE_PRODUCT = "dbo.USP_DELETE_BASE_DISCOUNT_PRICE_PRODUCT @PROCESS_ID, @IDX"; 

        //2014.12.08일 추가
        public const string USP_MERGE_BASE_DISCOUNT_PRICE_CUSTOMER = "[dbo].[USP_MERGE_BASE_DISCOUNT_PRICE_CUSTOMER] @PROCESS_ID, @CUSTOMER_CODE, @CUSTOMER_NAME, @CREATOR_ID";
        public const string USP_DELETE_BASE_DISCOUNT_PRICE_CUSTOMER_ALL = "[dbo].[USP_DELETE_BASE_DISCOUNT_PRICE_CUSTOMER_ALL] @PROCESS_ID";
        public const string USP_SELECT_BASE_DISCOUNT_PRICE_CUSTOMER = "[dbo].[USP_SELECT_BASE_DISCOUNT_PRICE_CUSTOMER] @PROCESS_ID";

        #endregion

        #region [ 39. IT Resource ]

        public const string USP_MERGE_IT_RESOURCE = "[dbo].[USP_MERGE_IT_RESOURCE] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID "
                                                + ", @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @CATEGORY, @TYPE, @RESOURCE "
                                                + ", @LOSS_REASON, @SECURITY_REPORT, @STATE, @COMPUTER_TYPE, @COMPUTER_MODEL, @MOBILE_MODEL "
                                                + ", @MOBILE_COLOR, @NEW_MODEL, @NEW_PURPOSE, @SOFTWARE_TYPE, @SOFTWARE_PURPOSE, @IS_PERMANENT, @SOFTWARE_FROM "
                                                + ", @SOFTWARE_TO, @SERVICE_TYPE, @SERVICE_ACCOUNT_NAME, @SERVICE_MDM_MODEL, @SERVICE_MDM_MAC, @SERVICE_MDM_SERIAL_NUMBER, @SERVICE_MDM_PHONE_NUMBER "
                                                + ", @SERVICE_IPT_PHONE, @SERVICE_IPT_MAC, @SERVICE_IPT_MODEL "
                                                + ", @SERVICE_BYOS_AGREE, @SERVICE_PURPOSE, @SERVICE_FROM, @SERVICE_TO, @IS_DISUSED, @CREATOR_ID";

        public const string USP_SELECT_IT_RESOURCE = "[dbo].[USP_SELECT_IT_RESOURCE] @PROCESS_ID";

        #endregion

        #region [ 40. BMSK Price]

        public const string USP_MERGE_BMSK_PRICE = "[dbo].[USP_MERGE_BMSK_PRICE] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @CUSTOMER_CODE, @CUSTOMER_NAME, @IS_DISUSED, @CREATOR_ID";

        public const string USP_INSERT_BMSK_PRICE_LIST = "[dbo].[USP_INSERT_BMSK_PRICE_LIST] @PROCESS_ID, @IDX, @MATERIAL_CODE, @MATERIAL_NAME, @BASE_PRICE, @TARGET_MIN_PRICE, @REQUEST_PRICE, @CURRENCY, @FROM_DATE, @TO_DATE, @CREATOR_ID";

        public const string USP_DELETE_BMSK_PRICE_LIST_ALL = "[dbo].[USP_DELETE_BMSK_PRICE_LIST_ALL] @PROCESS_ID";

        public const string USP_DELETE_BMSK_PRICE_LIST = "[dbo].[USP_DELETE_BMSK_PRICE_LIST] @PROCESS_ID, @IDX";

        public const string USP_SELECT_BMSK_PRICE = "[dbo].[USP_SELECT_BMSK_PRICE] @PROCESS_ID";

        public const string USP_SELECT_BMSK_PRICE_LIST = "[dbo].[USP_SELECT_BMSK_PRICE_LIST] @PROCESS_ID";

        #endregion

        #region [ 41. BMSK Rebate]

        public const string USP_SELECT_BMSK_REBATE = "dbo.USP_SELECT_BMSK_REBATE @PROCESS_ID";
        public const string USP_SELECT_BMSK_REBATE_CUSTOMER = "dbo.USP_SELECT_BMSK_REBATE_CUSTOMER @PROCESS_ID";
        public const string USP_SELECT_BMSK_REBATE_PRODUCT = "dbo.USP_SELECT_BMSK_REBATE_PRODUCT @PROCESS_ID";
        public const string USP_MERGE_BMSK_REBATE = "dbo.USP_MERGE_BMSK_REBATE @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE, @BU, @VALIDITY_FROM, @VALIDITY_TO, @TARGET_PERFORM, @ESTIMATED_PERFORM, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";
        public const string USP_MERGE_BMSK_REBATE_PRODUCT = "dbo.USP_MERGE_BMSK_REBATE_PRODUCT @PROCESS_ID, @PRODUCT_CODE, @IDX, @PRODUCT_NAME, @ACCRUAL, @CREATOR_ID, @CREATE_DATE";
        public const string USP_DELETE_BMSK_REBATE_CUSTOMER_ALL = "dbo.USP_DELETE_BMSK_REBATE_CUSTOMER_ALL @PROCESS_ID";
        public const string USP_DELETE_BMSK_REBATE_PRODUCT = "dbo.USP_DELETE_BMSK_REBATE_PRODUCT @PROCESS_ID, @IDX";
        public const string USP_DELETE_BMSK_REBATE_PRODUCT_ALL = "dbo.USP_DELETE_BMSK_REBATE_PRODUCT_ALL @PROCESS_ID";
        public const string USP_INSERT_BMSK_REBATE_CUSTOMER = "dbo.USP_INSERT_BMSK_REBATE_CUSTOMER @PROCESS_ID, @CUSTOMER_CODE, @CUSTOMER_NAME, @CREATOR_ID";
        #endregion

        #region [ 42. BCS AR Adjustment]
        
        public const string USP_SELECT_AR_ADJUSTMENT = "dbo.USP_SELECT_AR_ADJUSTMENT @PROCESS_ID";
        public const string USP_SELECT_AR_ADJUSTMENT_CUSTOMER = "dbo.USP_SELECT_AR_ADJUSTMENT_CUSTOMER @PROCESS_ID";
        public const string USP_SELECT_AR_ADJUSTMENT_PRODUCT = "dbo.USP_SELECT_AR_ADJUSTMENT_PRODUCT @PROCESS_ID";
        public const string USP_MERGE_AR_ADJUSTMENT = "dbo.USP_MERGE_AR_ADJUSTMENT @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE_CODE, @BG, @DISTRIBUTION_CHANNEL, @NH_CHANNEL, @ADJUST_AMOUNT, @OVER_LIMIT, @PURPOSE_DESC, @REASON, @REASON_CHECK, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";
        public const string USP_MERGE_AR_ADJUSTMENT_CUSTOMER = "dbo.USP_MERGE_AR_ADJUSTMENT_CUSTOMER @PROCESS_ID, @CUSTOMER_CODE, @CUSTOMER_NAME, @CREATOR_ID";
        public const string USP_MERGE_AR_ADJUSTMENT_PRODUCT = "dbo.USP_MERGE_AR_ADJUSTMENT_PRODUCT @PROCESS_ID, @IDX, @PRODUCT_CODE, @PRODUCT_NAME, @QTY, @PRICE, @AMOUNT, @PRODUCT_RB, @ADDITIONAL, @AFFECTED_PERCENT, @ADDITION_AMOUNT, @CREATOR_ID, @CREATE_DATE";
        public const string USP_DELETE_AR_ADJUSTMENT_CUSTOMER_ALL = "dbo.USP_DELETE_AR_ADJUSTMENT_CUSTOMER_ALL @PROCESS_ID";
        public const string USP_DELETE_AR_ADJUSTMENT_PRODUCT_ALL = "dbo.USP_DELETE_AR_ADJUSTMENT_PRODUCT_ALL @PROCESS_ID";

        #endregion

        #region [ 49. CS Exception Reqeust]

        public const string USP_SELECT_CS_EXCEPTION_REQUEST = "dbo.USP_SELECT_CS_EXCEPTION_REQUEST @PROCESS_ID";
        public const string USP_SELECT_CS_EXCEPTION_REQUEST_PRODUCT = "dbo.USP_SELECT_CS_EXCEPTION_REQUEST_PRODUCT @PROCESS_ID";
        public const string USP_MERGE_CS_EXCEPTION_REQUEST = "dbo.USP_MERGE_CS_EXCEPTION_REQUEST @PROCESS_ID,@SUBJECT,@DOC_NUM,@PROCESS_STATUS,@REQUESTER_ID,@REQUEST_DATE,@COMPANY_CODE,@ORGANIZATION_NAME,@LIFE_CYCLE,@TITLE_CODE,@BG,@DISTRIBUTION_CHANNEL,@NH_CHANNEL,@CUSTOMER_CODE,@CUSTOMER_NAME,@ADJUST_AMOUNT,@COMMENT,@EXCEPTION_REASON,@EXCEPTION_TITLE,@EXCEPTION_BACKGROUND,@EXCEPTION_PROPOSAL,@EXCEPTION_PROCESS,@EXCEPTION_FINANCIAL_IMPACK,@EXCEPTION_COMMENT,@IS_DISUSED,@CREATOR_ID,@CREATE_DATE	";
        public const string USP_MERGE_CS_EXCEPTION_REQUEST_PRODUCT = "dbo.USP_MERGE_CS_EXCEPTION_REQUEST_PRODUCT @PROCESS_ID,@IDX,@PRODUCT_CODE,@PRODUCT_NAME,@QTY,@INVOICE_PRICE,@INVOICE_AMOUNT,@ADDITIONAL,@VS_INV,@VOLUME_RB,@PROPOSAL_PRICE,@PROPOSAL_AMOUNT,@SUBSIDY_UNIT_PRICE,@NET2_PRICE,@CREATOR_ID,@CREATE_DATE";
        public const string USP_DELETE_CS_EXCEPTION_REQUEST_PRODUCT_ALL = "dbo.USP_DELETE_CS_EXCEPTION_REQUEST_PRODUCT_ALL @PROCESS_ID";

        #endregion

        #region [ 50. CS Sugsidy case]

        public const string USP_SELECT_CS_SUBSIDY_REQUEST = "dbo.USP_SELECT_CS_SUBSIDY_REQUEST @PROCESS_ID";
        public const string USP_SELECT_CS_SUBSIDY_REQUEST_PRODUCT = "dbo.USP_SELECT_CS_SUBSIDY_REQUEST_PRODUCT @PROCESS_ID";
        public const string USP_MERGE_CS_SUBSIDY_REQUEST = "dbo.USP_MERGE_CS_SUBSIDY_REQUEST @PROCESS_ID,@SUBJECT,@DOC_NUM,@PROCESS_STATUS,@REQUESTER_ID,@REQUEST_DATE,@COMPANY_CODE,@ORGANIZATION_NAME,@LIFE_CYCLE,@TITLE_CODE,@BG,@DISTRIBUTION_CHANNEL,@NH_CHANNEL,@CUSTOMER_CODE,@CUSTOMER_NAME,@ADJUST_AMOUNT,@COMMENT,@EXCEPTION_REASON,@EXCEPTION_TITLE,@EXCEPTION_BACKGROUND,@EXCEPTION_PROPOSAL,@EXCEPTION_PROCESS,@EXCEPTION_FINANCIAL_IMPACK,@EXCEPTION_COMMENT,@IS_DISUSED,@CREATOR_ID,@CREATE_DATE	";
        public const string USP_MERGE_CS_SUBSIDY_REQUEST_PRODUCT = "dbo.USP_MERGE_CS_SUBSIDY_REQUEST_PRODUCT @PROCESS_ID,@IDX,@PRODUCT_CODE,@PRODUCT_NAME,@QTY,@INVOICE_PRICE,@INVOICE_AMOUNT,@ADDITIONAL,@VS_INV,@VOLUME_RB,@BASIC_RB,@PROPOSAL_PRICE,@PROPOSAL_AMOUNT,@SUBSIDY_UNIT_PRICE,@NET2_PRICE,@CREATOR_ID,@CREATE_DATE";
        public const string USP_DELETE_CS_SUBSIDY_REQUEST_PRODUCT_ALL = "dbo.USP_DELETE_CS_SUBSIDY_REQUEST_PRODUCT_ALL @PROCESS_ID";

        #endregion

        #region [ 51. PH Exception Reqeust]

        public const string USP_SELECT_PH_EXCEPTION_REQUEST = "dbo.USP_SELECT_PH_EXCEPTION_REQUEST @PROCESS_ID";
        //public const string USP_SELECT_CS_EXCEPTION_REQUEST_PRODUCT = "dbo.USP_SELECT_CS_EXCEPTION_REQUEST_PRODUCT @PROCESS_ID";
        public const string USP_MERGE_PH_EXCEPTION_REQUEST = "dbo.USP_MERGE_PH_EXCEPTION_REQUEST @PROCESS_ID,@SUBJECT,@DOC_NUM,@PROCESS_STATUS,@REQUESTER_ID,@REQUEST_DATE,@COMPANY_CODE,@ORGANIZATION_NAME,@LIFE_CYCLE,@BU,@REASON,@TITLE,@CUSTOMER_CODE,@CUSTOMER_NAME,@PRODUCT,@BACKGROUND,@PROPOSAL,@PROCESS,@FINANCIAL_IMPACT,@COMMENT,@IS_DISUSED,@CREATOR_ID,@CREATE_DATE	";
        //public const string USP_MERGE_CS_EXCEPTION_REQUEST_PRODUCT = "dbo.USP_MERGE_CS_EXCEPTION_REQUEST_PRODUCT @PROCESS_ID,@IDX,@PRODUCT_CODE,@PRODUCT_NAME,@QTY,@INVOICE_PRICE,@INVOICE_AMOUNT,@ADDITIONAL,@VS_INV,@VOLUME_RB,@PROPOSAL_PRICE,@PROPOSAL_AMOUNT,@SUBSIDY_UNIT_PRICE,@NET2_PRICE,@CREATOR_ID,@CREATE_DATE";
        //public const string USP_DELETE_CS_EXCEPTION_REQUEST_PRODUCT_ALL = "dbo.USP_DELETE_CS_EXCEPTION_REQUEST_PRODUCT_ALL @PROCESS_ID";

        #endregion

        #region [43. BHC RETURN GOODS
        public const string USP_SELECT_BHC_RETURN_GOODS = "dbo.USP_SELECT_BHC_RETURN_GOODS @PROCESS_ID";

        public const string USP_MERGE_BHC_RETURN_GOODS = "dbo.USP_MERGE_BHC_RETURN_GOODS @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @COST_AMOUNT, @REMARK, @RETURN_GOODS_CODE, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";
        #endregion
        
        #region [ 44. Incident Report
        public const string USP_SELECT_INCIDENT_REPORT = "dbo.USP_SELECT_INCIDENT_REPORT @PROCESS_ID";

        public const string USP_MERGE_INCIDENT_REPORT = "dbo.USP_MERGE_INCIDENT_REPORT @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @OCCUR_DATE, @DETECT_DATE, @LOCATION, @DESCRIPTION, @DEVICE_TYPE, @ENCRYPT_YN, @EXPLAIN, @OTHERS, @COST, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        #endregion

        #region [ 45. BHC Compliance Review for Promotional Item

        public const string USP_SELECT_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL = "dbo.USP_SELECT_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL @PROCESS_ID";

        public const string USP_MERGE_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL = "dbo.USP_MERGE_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @PROMOTIONAL_MATERIAL, @UNIT_PRICE, @QTY, @AMT, @TOTAL_AMOUNT, @MATERIAL_TYPE, @TARGET_AUDIENCE, @PURPOSE, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_SELECT_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL_PRODUCT = "[dbo].[USP_SELECT_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL_PRODUCT] @PROCESS_ID";

        public const string USP_MERGE_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL_PRODUCT = "[dbo].[USP_MERGE_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL_PRODUCT] @PROCESS_ID, @PRODUCT_CODE, @PRODUCT_NAME, @CREATOR_ID";

        public const string USP_DELETE_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL_PRODUCT_ALL = "[dbo].[USP_DELETE_COMPLIANCE_REVIEW_FOR_PROMOTIONAL_MATERIAL_PRODUCT_ALL] @PROCESS_ID";

        public const string USP_DELETE_COMPLIANCE_BHC_PROMOTIONAL_MATERIAL = "[dbo].[USP_DELETE_COMPLIANCE_BHC_PROMOTIONAL_MATERIAL] @PROCESS_ID, @IDX";

        public const string USP_DELETE_COMPLIANCE_BHC_PROMOTIONAL_MATERIAL_ALL = "[dbo].[USP_DELETE_COMPLIANCE_BHC_PROMOTIONAL_MATERIAL_ALL] @PROCESS_ID";

        public const string USP_INSERT_COMPLIANCE_BHC_PROMOTIONAL_MATERIAL = "[dbo].[USP_INSERT_COMPLIANCE_BHC_PROMOTIONAL_MATERIAL] @PROCESS_ID, @IDX, @DESCRIPTION, @QTY, @UNIT_PRICE, @AMOUNT, @CREATOR_ID";

        public const string USP_SELECT_COMPLIANCE_BHC_PROMOTIONAL_MATERIAL = "[dbo].[USP_SELECT_COMPLIANCE_BHC_PROMOTIONAL_MATERIAL] @PROCESS_ID";

        #endregion

        #region [ 46. BCS Process Change

        public const string USP_SELECT_BCS_PROCESS_CHANGE = "dbo.USP_SELECT_BCS_PROCESS_CHANGE @PROCESS_ID";
        public const string USP_MERGE_BCS_PROCESS_CHANGE = "dbo.USP_MERGE_BCS_PROCESS_CHANGE @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE, @CATEGORY, @PURPOSE_TYPE, @DURATION_TYPE, @FROM_DATE, @TO_DATE, @BRIEF_DESCRIPTION, @EFFECT_BEFORE_AFTER, @AFFECTED_PRODUCT, @PROPOSED_DUE_DATE, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        #endregion

        #region [ 47. BHC new Price And Margin ]

        public const string USP_MERGE_BHC_PRICE_AND_MARGIN = "[dbo].[USP_MERGE_BHC_PRICE_AND_MARGIN] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @PRODUCT_FAMILY, @ATTACH_CHECK, @TYPE, @CHECK_CONFIG, @WHOLESALER_CODE, @WHOLESALER_NAME, @SECOND_WHOLESALER, @CONTRACT_FROM, @CONTRACT_TO, @CONTRACT_FROM_W_BKL, @CONTRACT_TO_W_BKL, @EXTENTION_AGREEMENT_CHECK, @RE_EWORKFLOW_DOC_NO, @EXTENSION_FROM_W_BKL, @EXTENSION_TO_W_BKL,  @REMARK,  @TOTAL_AMOUNT, @IS_DISUSED, @CREATOR_ID";

        public const string USP_MERGE_BHC_PRICE_AND_MARGIN_CUSTOMER = "[dbo].[USP_MERGE_BHC_PRICE_AND_MARGIN_CUSTOMER] @PROCESS_ID, @CUSTOMER_CODE, @CUSTOMER_NAME, @CREATOR_ID";

        public const string USP_MERGE_BHC_PRICE_AND_MARGIN_HOSPITAL = "[dbo].[USP_MERGE_BHC_PRICE_AND_MARGIN_HOSPITAL] @PROCESS_ID, @HOSPITAL_CODE, @HOSPITAL_NAME, @CREATOR_ID";

        public const string USP_MERGE_BHC_PRICE_AND_MARGIN_PRODUCT = "[dbo].[USP_MERGE_BHC_PRICE_AND_MARGIN_PRODUCT] @PROCESS_ID, @IDX, @PRODUCT_CODE, @PRODUCT_NAME,@SUPPLY_PRICE,@HOSPITAL_MARGIN,@WHOLESALER_MARGIN,@TOTAL_MARGIN,@VOLUME,@BASE_PRICE,@MARGIN_AS_IS,@MARGIN_TO_BE,@DISCOUNT_AMOUNT,@QTY,@AMOUNT,@REMARKS,@CREATOR_ID";

        public const string USP_DELETE_BHC_PRICE_AND_MARGIN_PRODUCT = "[dbo].[USP_DELETE_BHC_PRICE_AND_MARGIN_PRODUCT] @PROCESS_ID, @IDX";

        public const string USP_DELETE_BHC_PRICE_AND_MARGIN_CUSTOMER_ALL = "[dbo].[USP_DELETE_BHC_PRICE_AND_MARGIN_CUSTOMER_ALL] @PROCESS_ID";

        public const string USP_DELETE_BHC_PRICE_AND_MARGIN_HOSPITAL_ALL = "[dbo].[USP_DELETE_BHC_PRICE_AND_MARGIN_HOSPITAL_ALL] @PROCESS_ID";

        public const string USP_DELETE_BHC_PRICE_AND_MARGIN_PRODUCT_ALL = "[dbo].[USP_DELETE_BHC_PRICE_AND_MARGIN_PRODUCT_ALL] @PROCESS_ID";

        public const string USP_MERGE_BHC_PRICE_AND_MARGIN_DEAL_NO = "[dbo].[USP_MERGE_BHC_PRICE_AND_MARGIN_DEAL_NO] @PROCESS_ID,@DEAL_NO,@CREATOR_ID";

        public const string USP_SELECT_BHC_PRICE_AND_MARGIN = "[dbo].[USP_SELECT_BHC_PRICE_AND_MARGIN] @PROCESS_ID";

        public const string USP_SELECT_BHC_PRICE_AND_MARGIN_CUSTOMER = "[dbo].[USP_SELECT_BHC_PRICE_AND_MARGIN_CUSTOMER] @PROCESS_ID";

        public const string USP_SELECT_BHC_PRICE_AND_MARGIN_HOSPITAL = "[dbo].[USP_SELECT_BHC_PRICE_AND_MARGIN_HOSPITAL] @PROCESS_ID";

        public const string USP_SELECT_BHC_PRICE_AND_MARGIN_PRODUCT = "[dbo].[USP_SELECT_BHC_PRICE_AND_MARGIN_PRODUCT] @PROCESS_ID";

        #endregion

        #region [ 48. List Price ]
        public const string USP_INSERT_LIST_PRICE_PRODUCT = "[dbo].[USP_INSERT_LIST_PRICE_PRODUCT] @PROCESS_ID, @PRODUCT_CODE, @PRODUCT_NAME, @CURRENT_PRICE, @CURRENT_PRICE_INCLUDE_VAT, @BASE_PRICE, @REVISED_PRICE_INCLUDE_VAT, @REVISED_PRICE_EXCLUDE_VAT, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_MERGE_LIST_PRICE = "[dbo].[USP_MERGE_LIST_PRICE] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @CATEGORY, @BU, @DESCRIPTION, @CONTRACT_PERIOD_FROM, @CONTRACT_PERIOD_TO, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_SELECT_LIST_PRICE = "[dbo].[USP_SELECT_LIST_PRICE] @PROCESS_ID";

        public const string USP_SELECT_LIST_PRICE_PRODUCT = "[dbo].[USP_SELECT_LIST_PRICE_PRODUCT] @PROCESS_ID";

        public const string USP_DELETE_LIST_PRICE_PRODUCT = "[DBO].[USP_DELETE_LIST_PRICE_PRODUCT] @PROCESS_ID, @PRODUCT_CODE";

        public const string USP_DELETE_LIST_PRICE_PRODUCT_ALL = "[DBO].[USP_DELETE_LIST_PRICE_PRODUCT_ALL] @PROCESS_ID";
        #endregion

        #region [ 49. BVS Seed Import ]

        public const string USP_MERGE_BVS_SEED_IMPORT = "[dbo].[USP_MERGE_BVS_SEED_IMPORT] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TYPE, @EXPECTED_DATE, @VENDOR, @REMARK, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_MERGE_BVS_SEED_IMPORT_PRODUCT = "[dbo].[USP_MERGE_BVS_SEED_IMPORT_PRODUCT] @PROCESS_ID, @IDX, @PRODUCT_CODE, @PRODUCT_NAME, @CROP, @VARIETY, @SF_ST, @TP_PRICE, @QTY_EA, @AMOUNT, @FACTOR, @QTY_TH, @CREATOR_ID";

        public const string USP_SELECT_BVS_SEED_IMPORT = "[dbo].[USP_SELECT_BVS_SEED_IMPORT] @PROCESS_ID";

        public const string USP_SELECT_BVS_SEED_IMPORT_PRODUCT = "[dbo].[USP_SELECT_BVS_SEED_IMPORT_PRODUCT] @PROCESS_ID";

        public const string USP_DELETE_BVS_SEED_IMPORT_PRODUCT = "[dbo].[USP_DELETE_BVS_SEED_IMPORT_PRODUCT] @PROCESS_ID, @IDX";

        public const string USP_DELETE_BVS_SEED_IMPORT_PRODUCT_ALL = "[dbo].[USP_DELETE_BVS_SEED_IMPORT_PRODUCT_ALL] @PROCESS_ID";
        
        #endregion

        #region [ 50. Cs Credit Limit Approval ]

        public const string USP_SELECT_CS_CREDIT_LIMIT_APPROVAL = "dbo.USP_SELECT_CS_CREDIT_LIMIT_APPROVAL @PROCESS_ID";
        public const string USP_MERGE_CS_CREDIT_LIMIT_APPROVAL = "dbo.USP_MERGE_CS_CREDIT_LIMIT_APPROVAL @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @IS_ALL, @BU, @CUSTOMER_CODE, @CUSTOMER_NAME, @AMOUNT, @DESCRIPTION, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";

        #endregion

        #region [ 51. BCS Compensation]

        public const string USP_SELECT_BCS_COMPENSATION = "dbo.USP_SELECT_BCS_COMPENSATION @PROCESS_ID";
        public const string USP_SELECT_BCS_COMPENSATION_PRODUCT = "dbo.USP_SELECT_BCS_COMPENSATION_PRODUCT @PROCESS_ID";
        public const string USP_MERGE_BCS_COMPENSATION = "dbo.USP_MERGE_BCS_COMPENSATION @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE, @BU, @COMPLAINT_TYPE, @COMPLAINT_REPORT_NO, @REASON, @RECEVING_COMPENSATION_NAME, @RECEVING_COMPENSATION_ADDRESS, @COMPENSATION_TYPE, @PRODUCT_AMOUNT, @CASH_AMOUNT, @REMARK, @ATTACH_CHECK, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";
        public const string USP_MERGE_BCS_COMPENSATION_PRODUCT = "dbo.USP_MERGE_BCS_COMPENSATION_PRODUCT @PROCESS_ID, @IDX, @PRODUCT_CODE, @PRODUCT_NAME, @QTY, @PRICE, @AMOUNT, @COST_CODE, @COST_NAME, @LOCATION_CODE, @LOCATION_NAME, @REMARK, @CREATOR_ID, @CREATE_DATE";
        public const string USP_DELETE_BCS_COMPENSATION_PRODUCT_ALL = "dbo.USP_DELETE_BCS_COMPENSATION_PRODUCT_ALL @PROCESS_ID";
        public const string USP_DELETE_BCS_COMPENSATION_PRODUCTS = "dbo.USP_DELETE_BCS_COMPENSATION_PRODUCTS @PROCESS_ID, @IDX";

        #endregion

        #region [ 52. CS FM to NH Sales]

        public const string USP_DELETE_CS_FM_TO_NH_SALE_PRODUCT = "dbo.USP_DELETE_CS_FM_TO_NH_SALE_PRODUCT @PROCESS_ID, @IDX";
        public const string USP_DELETE_CS_FM_TO_NH_SALE_PRODUCT_ALL = "dbo.USP_DELETE_CS_FM_TO_NH_SALE_PRODUCT_ALL @PROCESS_ID";
        public const string USP_MERGE_CS_FM_TO_NH_SALE = "dbo.USP_MERGE_CS_FM_TO_NH_SALE @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @SOLD_TO_CUSTOMER_FM, @SOLD_TO_CUSTOMER_FM_NAME, @SHIP_TO_CUSTOMER_NH, @SHIP_TO_CUSTOMER_NH_NAME, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";
        public const string USP_MERGE_CS_FM_TO_NH_SALE_PRODUCT = "dbo.USP_MERGE_CS_FM_TO_NH_SALE_PRODUCT @PROCESS_ID, @IDX, @PRODUCT_CODE, @PRODUCT_NAME, @QTY, @PRICE, @AMOUNT, @SHIP_TO_CUSTOMER_NH, @SHIP_TO_CUSTOMER_NH_NAME, @CREATOR_ID, @CREATE_DATE";
        public const string USP_SELECT_CS_FM_TO_NH_SALE = "dbo.USP_SELECT_CS_FM_TO_NH_SALE @PROCESS_ID";
        public const string USP_SELECT_CS_FM_TO_NH_SALE_PRODUCT = "dbo.USP_SELECT_CS_FM_TO_NH_SALE_PRODUCT @PROCESS_ID";

        #endregion

        #region [ 53. AH Promotional Activity]

        public const string USP_DELETE_AH_P_I_ACTIVITY_COST_DETAIL = "dbo.USP_DELETE_AH_P_I_ACTIVITY_COST_DETAIL @PROCESS_ID, @IDX";
        public const string USP_DELETE_AH_P_I_ACTIVITY_COST_DETAIL_ALL = "dbo.USP_DELETE_AH_P_I_ACTIVITY_COST_DETAIL_ALL @PROCESS_ID";
        public const string USP_INSERT_AH_P_I_ACTIVITY_COST_DETAIL = "dbo.USP_INSERT_AH_P_I_ACTIVITY_COST_DETAIL @PROCESS_ID, @IDX, @CATEGORY_CODE, @CATEGORY_NAME, @DESCRIPTION, @QTY, @UNIT_PRICE, @AMOUNT, @CREATOR_ID";
        public const string USP_MERGE_AH_P_I_ACTIVITY = "[dbo].[USP_MERGE_AH_P_I_ACTIVITY] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE, @BU, @ACTIVITY_TYPE, @INCENTIVE_AGREEMENT, @INCENTIVE_CHECKLIST, @COST_CENTER, @MEETING_VENUE, @FROM_DATE, @TO_DATE, @ADDRESS_VENUE, @PURPOSE, @RELEVANT_E_WORKFLOW_NO, @GO_NUM, @NON_GO_NUM, @FARMER_NUM, @BAYER_EMPLOYEE_NUM, @TOTAL_AMOUNT, @IS_DISUSED, @CREATOR_ID, @EXISTS_PROMOTIONAL";
        public const string USP_SELECT_AH_P_I_ACTIVITY = "dbo.USP_SELECT_AH_P_I_ACTIVITY @PROCESS_ID";
        public const string USP_SELECT_AH_P_I_ACTIVITY_COST_DETAIL = "dbo.USP_SELECT_AH_P_I_ACTIVITY_COST_DETAIL @PROCESS_ID";
        public const string USP_SELECT_COMMON_AH_P_I_ACTIVITY = "dbo.USP_SELECT_AH_P_I_ACTIVITY_COST_DETAIL @YEAR";



        #endregion

        #region [ 54. CS Sales Recognition]

        public const string USP_SELECT_CS_SALES_RECOGNITION = "dbo.USP_SELECT_CS_SALES_RECOGNITION @PROCESS_ID";
        public const string USP_SELECT_CS_SALES_RECOGNITION_PRODUCT = "dbo.USP_SELECT_CS_SALES_RECOGNITION_PRODUCT @PROCESS_ID";
        public const string USP_MERGE_CS_SALES_RECOGNITION = "dbo.USP_MERGE_CS_SALES_RECOGNITION @PROCESS_ID,@SUBJECT,@DOC_NUM,@PROCESS_STATUS,@REQUESTER_ID,@REQUEST_DATE,@COMPANY_CODE,@ORGANIZATION_NAME,@LIFE_CYCLE, @BU, @CUSTOMER_CODE,@CUSTOMER_NAME,@REASON,@COMMENT, @IS_DISUSED,@CREATOR_ID,@CREATE_DATE	";
        public const string USP_MERGE_CS_SALES_RECOGNITION_PRODUCT = "dbo.USP_MERGE_CS_SALES_RECOGNITION_PRODUCT @PROCESS_ID,@IDX,@PRODUCT_CODE,@PRODUCT_NAME,@QTY,@CREATOR_ID,@CREATE_DATE";
        public const string USP_DELETE_CS_SALES_RECOGNITION_PRODUCT_ALL = "dbo.USP_DELETE_CS_SALES_RECOGNITION_PRODUCT_ALL @PROCESS_ID";

        #endregion

        #region [ 55. Rx Volume Data Collection ]
        public const string USP_MERGE_RX_VOLUME_DATA_COLLECTION = "[dbo].[USP_MERGE_RX_VOLUME_DATA_COLLECTION] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @COLLECTED_PRODUCT, @DATA_SOURCE, @DETAILS_OF_RX_VOLUME_DATA, @DETAILS_OF_RX_VOLUME_DATA_YN, @INCLUDING_COMPETITIVE_DATA_AND_DETAILS, @INCLUDING_COMPETITIVE_DATA_AND_DETAILS_YN, @PURPOSE_OF_COLLECTION, @COLLECTION_METHOD, @VALIDITY_DATE, @ARCHIVING_OF_DATA, @ACCESS_RIGHT,  @IS_DISUSED, @CREATOR_ID, @CREATE_DATE, @UPDATER_ID, @UPDATE_DATE";

        public const string USP_SELECT_RX_VOLUME_DATA_COLLECTION = "[dbo].[USP_SELECT_RX_VOLUME_DATA_COLLECTION] @PROCESS_ID";
        #endregion
        
        #region [ 56. Customer Complaint/Claim Handling ]

        public const string USP_SELECT_CUSTOMER_COMPLAINT_HANDLING = "dbo.USP_SELECT_CUSTOMER_COMPLAINT_HANDLING @PROCESS_ID";

        public const string USP_SELECT_CUSTOMER_COMPLAINT_HANDLING_PRODUCT = "dbo.USP_SELECT_CUSTOMER_COMPLAINT_HANDLING_PRODUCT @PROCESS_ID";

        public const string USP_MERGE_CUSTOMER_COMPLAINT_HANDLING = "dbo.USP_MERGE_CUSTOMER_COMPLAINT_HANDLING @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BG, @TYPE, @COMMENT, @CUSTOMER_TYPE, @CUSTOMER_CODE, @CUSTOMER_NAME, @ISSUE_AREA, @FARMER_NAME, @FARMER_TEL_NO, @FARMER_ADDRESS, @ISSUE_DATE, @ISSUE_EXPIRED_PERIOD, @ISSUE_COLLECTING_METHOD, @ACTION_AFTER_RECEPTION, @CONTACT, @EMPLOYEE, @ACTION_AFTER_VISIT, @ISSUE_CODE, @ISSUE_DESC,  @ISSUE_REMARK, @IS_DISUSED, @CREATOR_ID, @CREATE_DATE";

        public const string USP_MERGE_CUSTOMER_COMPLAINT_HANDLING_PRODUCT = "dbo.USP_MERGE_CUSTOMER_COMPLAINT_HANDLING_PRODUCT @PROCESS_ID, @IDX, @PRODUCT_CODE, @PRODUCT_NAME, @DEMAND_CODE, @DEMAND_NAME, @POPULATION_NO, @ISSUE_QTY, @ISSUE_UNIT, @ISSUE_TEXT, @CREATOR_ID, @CREATE_DATE";

        public const string USP_DELETE_CUSTOMER_COMPLAINT_HANDLING_PRODUCT = "dbo.USP_DELETE_CUSTOMER_COMPLAINT_HANDLING_PRODUCT @PROCESS_ID, @IDX";

        public const string USP_DELETE_CUSTOMER_COMPLAINT_HANDLING_PRODUCT_ALL = "dbo.USP_DELETE_CUSTOMER_COMPLAINT_HANDLING_PRODUCT_ALL @PROCESS_ID";

        #endregion

        #region [ 57. BKL Price And Margin (VER 3) DOCUMENT_ID = D0056 ]

        public const string USP_MERGE_BKL_PRICE_AND_MARGIN = "[dbo].[USP_MERGE_BKL_PRICE_AND_MARGIN] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @PRODUCT_FAMILY, @ATTACH_CHECK, @TYPE, @CHECK_CONFIG, @WHOLESALER_CODE, @WHOLESALER_NAME, @SECOND_WHOLESALER, @CONTRACT_FROM, @CONTRACT_TO, @CONTRACT_FROM_W_BKL, @CONTRACT_TO_W_BKL, @EXTENTION_AGREEMENT_CHECK, @RE_EWORKFLOW_DOC_NO, @EXTENSION_FROM_W_BKL, @EXTENSION_TO_W_BKL,  @REMARK,  @TOTAL_AMOUNT, @IS_DISUSED, @CREATOR_ID";

        public const string USP_MERGE_BKL_PRICE_AND_MARGIN_CUSTOMER = "[dbo].[USP_MERGE_BKL_PRICE_AND_MARGIN_CUSTOMER] @PROCESS_ID, @CUSTOMER_CODE, @CUSTOMER_NAME, @CREATOR_ID";

        public const string USP_MERGE_BKL_PRICE_AND_MARGIN_HOSPITAL = "[dbo].[USP_MERGE_BKL_PRICE_AND_MARGIN_HOSPITAL] @PROCESS_ID, @HOSPITAL_CODE, @HOSPITAL_NAME, @CREATOR_ID";

        public const string USP_MERGE_BKL_PRICE_AND_MARGIN_PRODUCT = "[dbo].[USP_MERGE_BKL_PRICE_AND_MARGIN_PRODUCT] @PROCESS_ID, @IDX, @PRODUCT_CODE, @PRODUCT_NAME,@SUPPLY_PRICE,@PASS_THROUGH_MARGIN,@WHOLESALER_MARGIN,@TOTAL_MARGIN,@VOLUME,@BASE_PRICE,@MARGIN_AS_IS,@MARGIN_TO_BE, @NORMAL_DISCOUNT, @CONDITIONAL_PRODUCT_DISCOUNT, @PARTNER_BASED_DISCOUNT, @TRANSACTION_DISCOUNT, @DISCOUNT_AMOUNT,@QTY,@AMOUNT,@REMARKS,@CREATOR_ID";

        public const string USP_DELETE_BKL_PRICE_AND_MARGIN_PRODUCT = "[dbo].[USP_DELETE_BKL_PRICE_AND_MARGIN_PRODUCT] @PROCESS_ID, @IDX";

        public const string USP_DELETE_BKL_PRICE_AND_MARGIN_CUSTOMER_ALL = "[dbo].[USP_DELETE_BKL_PRICE_AND_MARGIN_CUSTOMER_ALL] @PROCESS_ID";

        public const string USP_DELETE_BKL_PRICE_AND_MARGIN_HOSPITAL_ALL = "[dbo].[USP_DELETE_BKL_PRICE_AND_MARGIN_HOSPITAL_ALL] @PROCESS_ID";

        public const string USP_DELETE_BKL_PRICE_AND_MARGIN_PRODUCT_ALL = "[dbo].[USP_DELETE_BKL_PRICE_AND_MARGIN_PRODUCT_ALL] @PROCESS_ID";

        public const string USP_MERGE_BKL_PRICE_AND_MARGIN_DEAL_NO = "[dbo].[USP_MERGE_BKL_PRICE_AND_MARGIN_DEAL_NO] @PROCESS_ID,@DEAL_NO,@CREATOR_ID";

        public const string USP_SELECT_BKL_PRICE_AND_MARGIN = "[dbo].[USP_SELECT_BKL_PRICE_AND_MARGIN] @PROCESS_ID";

        public const string USP_SELECT_BKL_PRICE_AND_MARGIN_CUSTOMER = "[dbo].[USP_SELECT_BKL_PRICE_AND_MARGIN_CUSTOMER] @PROCESS_ID";

        public const string USP_SELECT_BKL_PRICE_AND_MARGIN_HOSPITAL = "[dbo].[USP_SELECT_BKL_PRICE_AND_MARGIN_HOSPITAL] @PROCESS_ID";

        public const string USP_SELECT_BKL_PRICE_AND_MARGIN_PRODUCT = "[dbo].[USP_SELECT_BKL_PRICE_AND_MARGIN_PRODUCT] @PROCESS_ID";

        #endregion

        #region [ 58. Internal Event DOCUMENT_ID = D0057]

        public const string USP_DELETE_INTERNAL_EVENT_COST_DETAIL = "dbo.USP_DELETE_INTERNAL_EVENT_COST_DETAIL @PROCESS_ID, @IDX";
        public const string USP_DELETE_INTERNAL_EVENT_COST_DETAIL_ALL = "dbo.USP_DELETE_INTERNAL_EVENT_COST_DETAIL_ALL @PROCESS_ID";
        public const string USP_INSERT_INTERNAL_EVENT_COST_DETAIL = "dbo.USP_INSERT_INTERNAL_EVENT_COST_DETAIL @PROCESS_ID, @IDX, @CATEGORY_CODE, @CATEGORY_NAME, @DESCRIPTION, @QTY, @UNIT_PRICE, @AMOUNT, @CREATOR_ID";
        public const string USP_MERGE_INTERNAL_EVENT = "dbo.USP_MERGE_INTERNAL_EVENT @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE, @BU, @ACTIVITY_TYPE, @INCENTIVE_AGREEMENT, @INCENTIVE_CHECKLIST, @COST_CENTER, @MEETING_VENUE, @FROM_DATE, @TO_DATE, @ADDRESS_VENUE, @PURPOSE, @RELEVANT_E_WORKFLOW_NO, @GO_NUM, @NON_GO_NUM, @FARMER_NUM, @BAYER_EMPLOYEE_NUM, @TOTAL_AMOUNT, @IS_DISUSED, @CREATOR_ID, @EXISTS_PROMOTIONAL";
        public const string USP_SELECT_INTERNAL_EVENT = "dbo.USP_SELECT_INTERNAL_EVENT @PROCESS_ID";
        public const string USP_SELECT_INTERNAL_EVENT_COST_DETAIL = "dbo.USP_SELECT_INTERNAL_EVENT_COST_DETAIL @PROCESS_ID";

        #endregion

        #region [ 59. BKL special price and discount DOCUMENT_ID = D0058 ]

        public const string USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT = "[dbo].[USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @BU, @PRODUCT_FAMILY, @ATTACH_CHECK, @TYPE, @CHECK_CONFIG, @WHOLESALER_CODE, @WHOLESALER_NAME, @SECOND_WHOLESALER, @CONTRACT_FROM, @CONTRACT_TO, @CONTRACT_FROM_W_BKL, @CONTRACT_TO_W_BKL, @EXTENTION_AGREEMENT_CHECK, @RE_EWORKFLOW_DOC_NO, @EXTENSION_FROM_W_BKL, @EXTENSION_TO_W_BKL,  @REMARK,  @TOTAL_AMOUNT,@EXCEPTION,@SAMEDISCOUNT, @IS_DISUSED, @CREATOR_ID";

        public const string USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT_CUSTOMER = "[dbo].[USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT_CUSTOMER] @PROCESS_ID, @CUSTOMER_CODE, @CUSTOMER_NAME, @CREATOR_ID";

        public const string USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT_HOSPITAL = "[dbo].[USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT_HOSPITAL] @PROCESS_ID, @HOSPITAL_CODE, @HOSPITAL_NAME, @CREATOR_ID";

        public const string USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT_PRODUCT = "[dbo].[USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT_PRODUCT] @PROCESS_ID,@IDX,@PRODUCT_CODE,@PRODUCT_NAME,@LIST_PRICE,@BASIC_DISCOUNT,@AS_IS_DISCOUNT,@TO_BE_DISCOUNT,@W_H_DISCOUNT,@VOLUME,@NET_AMOUNT,@NET_SELLING_PRICE,@DISCOUNT_RATE,@REMARKS,@CREATOR_ID";

        public const string USP_DELETE_BKL_SPECIAL_PRICE_AND_DISCOUNT_PRODUCT = "[dbo].[USP_DELETE_BKL_SPECIAL_PRICE_AND_DISCOUNT_PRODUCT] @PROCESS_ID, @IDX";

        public const string USP_DELETE_BKL_SPECIAL_PRICE_AND_DISCOUNT_CUSTOMER_ALL = "[dbo].[USP_DELETE_BKL_SPECIAL_PRICE_AND_DISCOUNT_CUSTOMER_ALL] @PROCESS_ID";

        public const string USP_DELETE_BKL_SPECIAL_PRICE_AND_DISCOUNT_HOSPITAL_ALL = "[dbo].[USP_DELETE_BKL_SPECIAL_PRICE_AND_DISCOUNT_HOSPITAL_ALL] @PROCESS_ID";

        public const string USP_DELETE_BKL_SPECIAL_PRICE_AND_DISCOUNT_PRODUCT_ALL = "[dbo].[USP_DELETE_BKL_SPECIAL_PRICE_AND_DISCOUNT_PRODUCT_ALL] @PROCESS_ID";

        public const string USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT_DEAL_NO = "[dbo].[USP_MERGE_BKL_SPECIAL_PRICE_AND_DISCOUNT_DEAL_NO] @PROCESS_ID,@DEAL_NO,@CREATOR_ID";

        public const string USP_SELECT_BKL_SPECIAL_PRICE_AND_DISCOUNT = "[dbo].[USP_SELECT_BKL_SPECIAL_PRICE_AND_DISCOUNT] @PROCESS_ID";

        public const string USP_SELECT_BKL_SPECIAL_PRICE_AND_DISCOUNT_CUSTOMER = "[dbo].[USP_SELECT_BKL_SPECIAL_PRICE_AND_DISCOUNT_CUSTOMER] @PROCESS_ID";

        public const string USP_SELECT_BKL_SPECIAL_PRICE_AND_DISCOUNT_HOSPITAL = "[dbo].[USP_SELECT_BKL_SPECIAL_PRICE_AND_DISCOUNT_HOSPITAL] @PROCESS_ID";

        public const string USP_SELECT_BKL_SPECIAL_PRICE_AND_DISCOUNT_PRODUCT = "[dbo].[USP_SELECT_BKL_SPECIAL_PRICE_AND_DISCOUNT_PRODUCT] @PROCESS_ID";
        #endregion


        #region [ 60. BKL Promotioal Activity ]

        public const string USP_MERGE_BKL_PROMOTIONAL_ACTIVITY = "[dbo].[USP_MERGE_BKL_PROMOTIONAL_ACTIVITY] @PROCESS_ID, @SUBJECT, @DOC_NUM, @PROCESS_STATUS, @REQUESTER_ID, @REQUEST_DATE, @COMPANY_CODE, @ORGANIZATION_NAME, @LIFE_CYCLE, @TITLE, @BU, @ACTIVITY_TYPE, @INCENTIVE_AGREEMENT, @INCENTIVE_CHECKLIST, @COST_CENTER, @PRODUCT_BRAND, @MEETING_VENUE, @FROM_DATE, @TO_DATE, @ADDRESS_VENUE, @PURPOSE, @RELEVANT_E_WORKFLOW_NO, @GO_NUM, @NON_GO_NUM, @FARMER_NUM, @BAYER_EMPLOYEE_NUM, @TOTAL_AMOUNT, @IS_DISUSED, @CREATOR_ID, @EXISTS_PROMOTIONAL";

        public const string USP_INSERT_BKL_PROMOTIONAL_ACTIVITY_COST_DETAIL = "[dbo].[USP_INSERT_BKL_PROMOTIONAL_ACTIVITY_COST_DETAIL] @PROCESS_ID, @IDX, @CATEGORY_CODE, @CATEGORY_NAME, @DESCRIPTION, @QTY, @UNIT_PRICE, @AMOUNT, @CREATOR_ID";

        public const string USP_DELETE_BKL_PROMOTIONAL_ACTIVITY_COST_DETAIL_ALL = "[dbo].[USP_DELETE_BKL_PROMOTIONAL_ACTIVITY_COST_DETAIL_ALL] @PROCESS_ID";

        public const string USP_DELETE_BKL_PROMOTIONAL_ACTIVITY_COST_DETAIL = "[dbo].[USP_DELETE_BKL_PROMOTIONAL_ACTIVITY_COST_DETAIL] @PROCESS_ID, @IDX";

        public const string USP_SELECT_BKL_PROMOTIONAL_ACTIVITY = "[dbo].[USP_SELECT_BKL_PROMOTIONAL_ACTIVITY] @PROCESS_ID";

        public const string USP_SELECT_BKL_PROMOTIONAL_ACTIVITY_COST_DETAIL = "[dbo].[USP_SELECT_BKL_PROMOTIONAL_ACTIVITY_COST_DETAIL] @PROCESS_ID";
        #endregion

    }
}
